### ISSUE TITLE
getting-paid.md has HTTP 404 Not Found link

### ISSUE THREAD

**Issue by patoi** [github/opensource.guide#1030]
"@mamiM did Japanese translations for @MetaMask after the issue was funded on Bounties Network." reference to https://beta.bounties.network/bounty/v1/134 which is missing.

**Comment by LalitoConstantino** [comment]
gem "github-linguist", "~> 7.5.1"

**Comment by maria1118** [comment]
Same issue..been working for almost a year no payments
