### ISSUE TITLE
RFC: Expand the funding section with a list of organizations/foundations

### ISSUE THREAD

**Issue by atodorov** [github/opensource.guide#1058]
As it is the funding section is a good start but I've been thinking about a detailed list of resources with a short info for them. 

For example Mozilla Foundation is likely to only sponsor projects which are related to what they do or somehow used by Mozilla infrastructure. 

The section doesn't even mention Google Summer of Code.

Will you accept a detailed list (to be expanded in time) of possible revenue sources ? I am willing to contribute the ones I know about, just let me know what format (where in the source) you would like this to live.

**Comment by mlinksva** [comment]
I think list proposals have been discussed before several times (first a quick search turns up is https://github.com/github/opensource.guide/issues/278#issuecomment-280356198) and the thought was that guides aren't a great place for them. I guess section you're referring to is https://github.com/github/opensource.guide/blob/b37d0de7cc8794666f03b45c353f668d1ba1a424/_articles/getting-paid.md#apply-for-grant-funding

Those are examples. If you have an idea for more clearly signaling that, or better examples, please say (or make a PR).

There is a link in that section to https://github.com/nayafia/lemonade-stand which is more listy but looking at it for the first time in awhile, not as list oriented as an awesome list. Maybe there's another link that could complement that.

GSoC isn't primarily a funding program for projects, I suspect is the reason it isn't mentioned there.

Just initial reactions, could be wrong, thanks for writing up the proposal.

**Comment by serliyasimarahmania** [comment]
Http://www.blockchain@example.com

**Comment by mlinksva** [comment]
Closing, see comments in #1111 and #1121. Thanks!
