### ISSUE TITLE
Add practical example how to copy code parts in legal guide

### ISSUE THREAD

**Issue by davidak** [github/opensource.guide#1084]
https://opensource.guide/legal/

It is not clear to me **how** i should practically note the copyright of a code part (for example 5 lines from a MIT project). Is it legally OK to just note the source, author and license in the commit message description or should it be in the header of the file or in the LICENSE file of the project?

When i copy whole files, the license header should not be removed. This is logical. But how to note that i made changes? Is it OK to just have them in git? How do i add myself to the copyright header as author?

Related: https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write

**Comment by mlinksva** [comment]
The guide doesn't directly address using code under third party OSS licenses. It would probably need a new section to get close to the level of detail that you're asking for. It's a reasonable idea. I'm not sure how soon I'll get to it, but please add comments with further resources that might be useful like the related link above.

**Comment by Rayad2361424** [comment]
https://github.com/github/opensource.guide/issues/1084

**Comment by Rayad2361424** [comment]
https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write

**Comment by Rayad2361424** [comment]
https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write

**Comment by davidak** [comment]
@Rayad2361424 what are you trying to do there? Please don't spam everyone subscribed to this issue.

**Comment by davidak** [comment]
this topic is still relevant

**Comment by fieproperty88** [comment]
> https://opensource.guide/legal/
> 
> Tidak jelas bagi saya **bagaimana** saya harus secara praktis mencatat hak cipta dari bagian kode (misalnya 5 baris dari proyek MIT). Apakah sah-sah saja untuk mencatat sumber, penulis, dan lisensi dalam deskripsi pesan commit atau haruskah berada di header file atau dalam file LICENSE proyek?
> 
> Saat saya menyalin seluruh file, tajuk lisensi tidak boleh dihapus. Ini logis. Tetapi bagaimana saya mencatat bahwa saya membuat perubahan? Apakah saya tetap bisa memilikinya di git? Bagaimana saya menambahkan diri saya ke header hak cipta sebagai penulis?
> 
> Terkait: https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write

**Comment by nilli54** [comment]
#1084

**Comment by MikeMcQuaid** [comment]
Closing this as at this point discussion on a PR is probably the only way forward. Thanks!
