### ISSUE TITLE
Travis CI test error on Links

### ISSUE THREAD

**Issue by patoi** [github/opensource.guide#1108]
I found a CI test error on my #1020 branch. This is Hungarian translation, but the error comes from _site/fr directory. This looks like a test _code_ error, because all other languages use the same URLs and there is 'no issues found'.

Travis CI event: https://travis-ci.org/github/opensource.guide/builds/586989750

```
111 runs, 896 assertions, 0 failures, 0 errors, 0 skips
[34mRunning ["ScriptCheck", "ImageCheck", "HtmlCheck", "OpenGraphCheck", "LinkCheck"] on ["_site"] on *.html... 

[0m
[34mChecking 518 external links...[0m
[34mRan on 123 files!

[0m
[31m- _site/fr/building-community/index.html[0m
[31m  *  External link https://github.com/karissa failed: 404 No error[0m
[31m- _site/fr/getting-paid/index.html[0m
[31m  *  External link https://blog.rackspace.com/rackspaces-policy-on-contributing-to-open-source/ failed: 404 No error[0m
/home/travis/.rvm/gems/ruby-2.4.3/gems/html-proofer-3.12.2/lib/html-proofer/runner.rb:172:in `print_failed_tests': [31mHTML-Proofer found 2 failures![0m (RuntimeError)
	from /home/travis/.rvm/gems/ruby-2.4.3/gems/html-proofer-3.12.2/lib/html-proofer/runner.rb:50:in `run'
	from script/html-proofer:23:in `<main>'
[4m[32m_articles/best-practices.md[39m[24m: no issues found
[4m[32m_articles/building-community.md[39m[24m: no issues found
[4m[32m_articles/code-of-conduct.md[39m[24m: no issues found
[4m[32m_articles/de/best-practices.md[39m[24m: no issues found
[4m[32m_articles/de/building-community.md[39m[24m: no issues found
[4m[32m_articles/de/code-of-conduct.md[39m[24m: no issues found
[4m[32m_articles/de/finding-users.md[39m[24m: no issues found
[4m[32m_articles/de/getting-paid.md[39m[24m: no issues found
[4m[32m_articles/de/how-to-contribute.md[39m[24m: no issues found
[4m[32m_articles/de/leadership-and-governance.md[39m[24m: no issues found
[4m[32m_articles/de/legal.md[39m[24m: no issues found
[4m[32m_articles/de/metrics.md[39m[24m: no issues found
[4m[32m_articles/de/starting-a-project.md[39m[24m: no issues found
```

**Comment by mlinksva** [comment]
html-proofer in my experience reports only one instance of a link failure, even if the link exists multiple times in a set of pages it is testing. Expected behavior.

However, there are a couple currently broken links that should be fixed across all translations. I'll try to do that soon, but if anyone else wishes to beat me to it, please do!

**Comment by patoi** [comment]
There are two types of errors.

**building-community.md:** @karissa GitHub account has been deleted. In `— @karissa, ["How to Run a FOSS Project"](https://okdistribute.xyz/post/okf-de)` line, the `@karissa` resolved to `https://github.com/karissa` which is response with 404.

**getting-paid.md:** on this page the content of the URL ref. has been deleted permanently. I've not found any other ref. to content...

**Comment by mlinksva** [comment]
Thanks! See fixes to be applied to translations in master in #1109.

**Comment by mlinksva** [comment]
(I acknowledge that ideally these fixes would be applied non-manually to the many WIP translation branches...if anyone wishes to point out a script to apply search/replace, commit, push across a set of branches, would be happy to use it!)
