### ISSUE TITLE
Process for translating a new article

### ISSUE THREAD

**Issue by mlinksva** [github/opensource.guide#1120]
Copying from https://github.com/github/opensource.guide/pull/985#issuecomment-524490596

> [we] might need to add something to tests to allow for not-yet-translated articles. I don't think any articles have been added since the original set so we haven't had the issue yet. Or maybe the right thing is to add stubs for to each translation for a new article asking for translations? Either would seem reasonable to me.

Think I prefer the stubs route: no test change needed, visible to people looking through `_articles/{lang}` who might be interested in translating.

**Comment by MikeMcQuaid** [comment]
I think the higher-level goal is "no new articles". I don't think we're at a place to really be able to accept them and give them a decent level of review. I also think the original set of articles stand alone nicely. Perhaps that should be documented explicitly somewhere?

**Comment by mlinksva** [comment]
I think the new article being worked on in #985 would be a worthy addition, and we have someone working on it. Happy to be wrong about even that one though. In any case, 👍 to documenting at least an extremely high bar for any new articles.
