### ISSUE TITLE
Needs to highlight open source cryptocurrency project funding

### ISSUE THREAD

**Issue by jdabs** [github/opensource.guide#1129]
I didn't see any mention of open source projects that tackle  funding in unique ways. Most examples shown rely on large private companies as resources or public fund raising through gofundme, etc.

Bitcoin (BTC), Monero coin (XMR), and many others in the cryptocurrency industry are on the cutting edge of experimenting with new funding solutions. Bitcoin has a "bounty" tags highlighting bugs that offer BTC payment as a reward for anyone who sends a patch:

https://github.com/bitcoin-dot-org/bitcoin.org/labels/Bounty

Monero funds projects through an open forum. Developers submit Proposals and gauge interest. Interested monero users can donate towards what the developer has asked for funding. The target contribution can be tracked. This is a unique way to pay developers to do work for open source projects that relies on consensus from members in the community. 

In general, I believe the opensource.guide website would do well to highlight new ideas in open source funding.

**Comment by mlinksva** [comment]
This project is more oriented toward highlighting existing best practices than new ideas. Currency, crypto or otherwise, seems orthogonal.

**Comment by jdabs** [comment]
That's the thing...there are no existing best practices. Funding open-source work is still experimental. Using two dollar words like "orthogonal" does not make ideas outside of this site's limited scope "wrong" in any sense. You make it sound like having private companies contribute (see facebook's licensing uproar with React) and community donation fun-raisers (which have sporadic participation) are tried-and-true long term solutions, while in fact the idea of funding open-source is a novel and difficult concept still in the works.
