### ISSUE TITLE
Suggestion: How to host a code sprint event

### ISSUE THREAD

**Issue by ohthehugemanatee** [github/opensource.guide#1141]
There's a great guide to this at https://github.com/drud/sprint_guide/blob/master/brilliant-sprints.md ... seems like it would fit in nicely here with other advice for maintainers. 

Assuming it's interesting to the maintainers, what's the right way to bring this content in? It's under the Creative Commons Attribution 4.0 International Public License, so technically we could just copypasta with an attribution link... Or perhaps we're considering a list of other helpful resources, and we could just link directly?

**Comment by MikeMcQuaid** [comment]
Thanks for the suggestions but we're not considering new guides at this time.
