### ISSUE TITLE
"Layout Default" box is seen at the top of CONTRIBUTING.md document & Table of contents start from 0th index

### ISSUE THREAD

**Issue by MrNoddyInfy** [github/opensource.guide#1154]
"Layout Default" box is seen at the top of CONTRIBUTING.md document & Table of contents start from 0th index. Screenshot attached for reference.

![Screenshot (90)](https://user-images.githubusercontent.com/53807772/67359351-a9820400-f580-11e9-946a-6c05035f8bb7.png)

**Comment by MrNoddyInfy** [comment]
I can fix this if it's issue.

**Comment by MikeMcQuaid** [comment]
This is not an issue.
