### ISSUE TITLE
 translations.md looks like needs lil improvement

### ISSUE THREAD

**Issue by ac2epsilon** [github/opensource.guide#1175]
Look, bullet 5 from  ..Copy `index.html`.. in the end says ..Remove the `toc:`.. However index has no any toc:s, while articles mentioned in bullet 4 do. So sentence ..Remove the `toc:`.. logically belongs rather to sooner bullet 4. I guess so, if you don;t mean something else

**Comment by mlinksva** [comment]
I think you're right. Want to submit a PR to fix it?

**Comment by mlinksva** [comment]
This was fixed by #1185
