### ISSUE TITLE
Portuguese title (typo) presentation problem

### ISSUE THREAD

**Issue by adriancf-br** [github/opensource.guide#1204]
This guide, when translated to portuguese presents one typo at the title.

Link to page:
https://opensource.guide/pt/how-to-contribute/

As I see in my Chrome navigator. "Como Cont ibuir para o Open Source."
As it should be "Como Contribuir para o Open Source."

In fact, the "r" letter is there but is not presentet.

**Comment by mlinksva** [comment]
It looks right to me, in multiple browsers. I can't imagine what would be producing the behavior you see @adriancf-br -- maybe include a screenshot?

**Comment by adriancf-br** [comment]
Yes, I can see it in IE browser but at Chrome, it looks like this scrrenshot.
Thanks @mlinksva  for your attetion.

![typoBR_pt](https://user-images.githubusercontent.com/26074280/69348552-21f9e480-0c55-11ea-8c41-0f4e4520267d.jpg)

**Comment by mlinksva** [comment]
Hmm, I have no idea what could be causing that, but I'm not a designer, know only the bare minimum about styles and fonts. 😬 

Could you say what exact version of Chrome you're using? Is the 'r' missing if you zoom in/out?

I'll leave this open for now in case there might be some evidence that this is a problem affecting more users, and one that someone who knows things I don't might have an idea about how to fix.

**Comment by adriancf-br** [comment]
Google Chrome Versão 78.0.3904.97 (Versão oficial) 64 bits.

Zoom in and out realy show and hide the letter.

**Comment by ralphg6** [comment]
Do you use windows? 
What resolution is set? 
Have you been able to reproduce on another computer?

**Comment by adriancf-br** [comment]
Yes, Windows 7, screen resolution 1360x768. In other computer, it works fine.

**Comment by ralphg6** [comment]
@adriancf-br unfortunately I could not reproduce this error for debugging. And I have no idea what could be causing that.

**Comment by adriancf-br** [comment]
@ralphg6,
I could not list plugins in Chrome navigator but I tested in the same machine for IE, Firefox, Tor and Chromium and this error is not reproduced only in MS IE browser. So, I suppose,  it s not a matter of navigator. May be a problem related to my Windows version. I wil try to update my so and report here later.

**Comment by iennae** [comment]
@adriancf-br it might also be something to do with your version of Chrome. 

I checked on Version 78.0.3904.108 (Official Build) (64-bit) and couldn't replicate, and there isn't special syntax on that title. Maybe try updating your Chrome as well. I did see this issue https://support.google.com/chrome/thread/2308245?msgid=6053985 that folks were reporting from earlier in the year.

**Comment by adriancf-br** [comment]
@iennae I reproduced this error on different browsers, so I believe it is not related to that bug. Firefox, for example, present the same error.

**Comment by MikeMcQuaid** [comment]
Passing on this as multiple people can't reproduce, sorry!
