### ISSUE TITLE
FLOSS or OSS?

### ISSUE THREAD

**Issue by ahangarha** [github/opensource.guide#1206]
Hi

First of all, thanks for the content you share.

I noticed all over the content, you talked Open Source. Regarding the old discussion around Free Software or Open Source I wanted to know what is the reason that there is no use of "Free Software", "Free and Open Source", "Free/Libre and Open Source", FOSS or FLOSS?

My stand is the in 99 percent of the cases, OSS is a Free Software as well. So, in almost all cases, we are talking about the same thing but referring to two different concepts. One refers to a dev model while the other refers to respecting users' freedom. I am in favor of valuing users' freedom and proudly and loudly expressing it. I am not asking to remove Open Source but add "Free/Libre" to it.

Would you accept if I make these changes and send PR?

**Comment by mlinksva** [comment]
I don't recall/can't find the details but before these guides were launched it was discussed which term to use and decided to use "open source" throughout. It seems reasonable to me to mention the different terms in the `What does "open source" mean?` section, which I've done in #1207.

Thanks for pointing out the omission.

**Comment by ahangarha** [comment]
I don't think this would fix the issue. If you are worried about people perceive Free Software as a freemium one, that can be handled in some way. But Open Source misses some critical point of Free Software which is Freedom of the user. Though as I mentioned above in 99 percent of the cases, a given software is at the same time Free Software and Open Source Software, but by just calling it Open Source, we miss the Freedom part of it which is perhaps the most important part.

More information: [Why Open Source misses the point of Free Software](https://www.gnu.org/philosophy/open-source-misses-the-point.html)

I think this project would be a good ground for improving awareness about the criticality of paying attention to the users' freedom which is reflected in Free/Libre and Open Source software.

**Comment by mlinksva** [comment]
OK, closing as won't fix then. We're not going to rename the project nor change every instance of "open source" in the guides. You are very free to publish a version with such edits, indeed I would enjoy seeing that.

And thanks again, even if my takeaway was not your intended point.

**Comment by ahangarha** [comment]
Just may I know the reason? I hope not because talking about software freedom is forbidden.

**Comment by iennae** [comment]
@ahangarha it sounds like you want a much broader change to the guides than the fix that @mlinksva proposed with PR #1207 and would change the scope of the project as it is. Just replacing open source with FLOSS would be a disservice to everyone looking for those specific nuances. I'm not a maintainer to the project so I'm not speaking for them in this comment. As mentioned above, it's possible for you to fork the project and create the FLOSS community guides which would be helpful for the community (keeping in mind the changes required).

**Comment by ahangarha** [comment]
I couldn't see any harm to the project by replacing Open Source with FLOSS. The emphasis on using Open Source instead on anything that refers freedom is not good. Yet, I respect your decision.

Of course I know I can fork the project, but this was not my goal. I hoped to have a constructive conversation to improve this project. I thought we might share same value which appeared to be false.

Anyway, I hope this to be changed on day. Looking forward to see we proudly talk about freedom

**Comment by hashlash** [comment]
**Disclaimer**: I'm not a Free Software nor Open Source Software expert and still have some confusion between these two terms, so please correct me if I'm wrong.

I think I understand the reasons pointed out by @mlinksva and @iennae, and I'm okay with it. But in my opinion, the change made in #1207 still miss some point.

> _Free software_ refers to the same set of projects as _open source_. Sometimes you'll also see [these terms](https://en.wikipedia.org/wiki/Free_and_open-source_software) combined as "free and open soruce software" (FOSS) or "free, libre, and open source software" (FLOSS). _Free_ and _libre_ refer to freedom, [not price](#does-open-source-mean-free-of-charge).

When I read it, especially the *"refers to the same set of projects"* phrase, I got the impression that Free Software is just the same as Open Source Software, while (I believe) this isn't true. There are [some set](https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences#Approvals) of Open Source Software which isn't compliant to Free Software definition and vice versa.

I know the differences are very subtle and may require a lot of explanations, so the page may not be the right place for explaining those differences. But still, I think the page needs to state that these two things are not the same thing and give some references for further explanation.

From [an article](https://www.digitalocean.com/community/tutorials/Free-vs-Open-Source-Software#the-differences-between-free-and-open-source-software) on DigitalOcean (emphasises are mine):

> Whether or not a given piece of software is free or open-source **depends on which license it’s distributed under and whether that license is approved by the Open Source Initiative, the Free Software Foundation, or both**. There’s a good deal of overlap between which licenses are approved by which organization, but there are a few exceptions. For example, the NASA Open Source Agreement is an OSI-approved license which the FSF views as too restrictive. Thus, the FSF discourages anyone from using software distributed under that license. Generally speaking, though, there’s a good chance that if it can be described as free software, it will fit the definition of open-source software as well.

**Comment by ahangarha** [comment]
Finding some software or license which is only compatible with on of FSF or OSI is very rare. Almost all the common licenses are accpeted by both and therefore, almost all the software we consider as Free Software are Open Source as well and vice versa.

The key point about the difference between the two is their values. Free Software emphasis on users' freedom while Open Source has no ethical value attached to it as it is a merely development model. Philosophically we can discuss why this is an important issue but I suggest read multiple articles published on Gnu and FSF websites in this regards.

To me, Freedom is critical. Yet I cannot force people to stop using misleading Open Source term. While mentioning the user freedom is [apparently] forbidden among Open Source camp, I am simply asking to use the combined term which is Free/Libre and Open Source or FLOSS or FOSS.

The resistance against doing so, is interesting. I don't know why users' freedom should be hidden. Why users shouldn't hear about their freedom and its importance? Answer is not very hard to guess. Yet, I try my best to improve the situation. I would appreciate any help.

**Comment by hashlash** [comment]
Ah right, I think the differentiation in *value* should also be mentioned. And perhaps also mentioning why the site decided to choose the term *Open Source Software* instead of *Free Software* (and *FOSS*/*FLOSS*)?

Btw, I really appreciate @ahangarha for speak up on behalf of freedom. And I like to thank you for the site contributors for maintaining such a great site. I learn a lot from it :blush:

**Comment by ahangarha** [comment]
No doubt this project is great.
