### ISSUE TITLE
The language code of Chinese should be changed

### ISSUE THREAD

**Issue by popcorner** [github/opensource.guide#1238]
This project is using zh-cn to represent simplified Chinese, and zh-tw to represent traditional Chinese. But this is not the best practice.
Actually, zh-cn means Chinese (mainland China), and zh-tw means Chinese (taiwan), but there are also many people using simplified and traditional Chinese in some places like Singapore and Hong Kong.

The real language code of simplified Chinese is **zh-hans**, and traditional Chinese is **zh-hant** (han means hanzi, Chinese character)

Ref: Microsoft's explanation in their document https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd997383(v=vs.100)#new-specific-cultures

**Comment by mlinksva** [comment]
Hmm, my impression was that eg zh-hant and zh-tw mean different things, the latter effectively being zh-hant-tw (script is usually omitted if possible). However the locale_name fields in _data/locales seem (autotranslation) to specify Simplified and Traditional, and hopefully the latter articles don't contain a lot of things that would be specific to tw and not eg hk. So I imagine your suggestion is correct. Another reference https://www.w3.org/International/articles/language-tags/#script

> Although for common uses of language tags it is not likely that you will need to specify the script, there are one or two situations that have been crying out for it for some time. One such example is Chinese. There are many Chinese dialects, often mutually unintelligible, but these dialects are all written using either Simplified or Traditional Chinese script. People typically want to label Chinese text as either Simplified or Traditional, but until recently there was no way to do so. People had to bend something like zh-CN (meaning Chinese as spoken in China) to mean Simplified Chinese, even in Singapore, and zh-TW (meaning Chinese as spoken in Taiwan) for Traditional Chinese. (Other people, however, use zh-HK for Traditional Chinese.) The availability of zh-Hans and zh-Hant for Chinese written in Simplified and Traditional scripts should improve consistency and accuracy, and is already becoming widely used, although of course you may need to continue to use the old language tags in some cases for consistency.

I made #1240 to show what this change would involve.

**Comment by popcorner** [comment]
@mlinksva Actually, my suggestion about using these language codes is according to the information from tech websites in Chinese, and their community made this conclusion and considered it as the best practice. So I think that is correct.
As for the region-specific problem, the fact is, spoken and written Chinese is different. Written Chinese in all the places is almost the same while spoken Chinese behaves differently. For example, the Chinese Wikipedia has been working for a long time, and their editors are from mainland China, Taiwan, Hong Kong, and Singapore. They can edit the same Wikipedia without confusion (Wikipedia can convert simplified and traditional Chinese characters automatically, and replace some specific words). Their relationship is just like English(US) and English(UK). There are differences but people can understand any of them, and most of the time it may not necessary to make specific versions for every region.

**Comment by MikeMcQuaid** [comment]
I'd like to see more input from more people before we make any changes here.

**Comment by mlinksva** [comment]
> I'd like to see more input from more people before we make any changes here.

💯 it seems worth pinging some contributors to the zh-* translations: @felixshai @lijiangsheng1 @jtr109 @jyangchisyan @WillemJiang

**Comment by felixshai** [comment]
Thanks for notification and references above. The translation works in **zh-tw** are mostly done by @jyangchisyan and me, and both of us are using Chinese (Traditional, Taiwan). Therefore I suggest **zh-tw -> zh-Hant-TW** such that it could leave a friendly space for **zh-Hant-CN/HK/MO/SG** if someone wants to contribute in the future.

**Comment by popcorner** [comment]
@felixshai Actually, most of the documents and software GUI only provides two kinds of Chinese so it may not possible to let this project have another version of Chinese translation, and that's also unnecessary. Although we come from specific region, our translation can also help people in other places.
And the reason that I make this suggestion is to follow the standard, but **zh-Hant-TW** is not a recommended language code. If we really need to show that the translation is only for specific region, keeping it unchange is just right. But when people from other region can read and understand these translations, limiting them to certain region might not be a good idea.

**Comment by felixshai** [comment]
TL;DL : I agree with  #1240 .

@popcorner In my intention, using region subtag is to provide friendly space for **zh-Hant-CN/HK/MO/SG** contributor in the future not to limit users to certain region. 
If we choose **zh-tw -> zh-Hant-TW** , it is recommended to change locale_name fields in _data/locales from **繁體中文** to **台灣繁體** to avoid confusion as @mlinksva mentioned above:

> ... However the locale_name fields in _data/locales seem (autotranslation) to specify Simplified and Traditional ...

As opensource.guide mentioned in "building-community", it is important to [keep the conversation focused on action](https://opensource.guide/building-community/#keep-the-conversation-focused-on-action). Despite the part about region tag, our mutual agreement is changing **zh-tw** to **zh-Hant** first. Therefore I'm OK with #1240
