### ISSUE TITLE
instruction about adding  new translation doesn't work for me

### ISSUE THREAD

**Issue by Aparus** [github/opensource.guide#1263]
Hi! I want to add russian translation. Of course I haven't translated all articles, but I tried to add full request with some parts of work. And faced problems. 
I wanted just make pull request for people know that somebody almost begun to do that work. Is it right? Can I open  pull request just for mark a start of work? 

I followed this [instruction for translators](https://github.com/github/opensource.guide/blob/master/docs/translations.md). 
I tried `test` in different ways: `npm run test`, `npm run script/test`, `npm test` and with sudo. 
But in any cases I faced errors. Like this one, and some others: 
![Screenshot from 2019-12-31 19-37-16](https://user-images.githubusercontent.com/1222611/71628183-c0d81000-2c07-11ea-924e-0b13cd499169.png)
I also tried to build the site in different ways, and I also faced errors. 

Please, complete the [instruction for translators](https://github.com/github/opensource.guide/blob/master/docs/translations.md) with additional info, about what to do before tests, how to create bundle, how to build a site etc.

**Comment by MikeMcQuaid** [comment]
> Can I open pull request just for mark a start of work?

Yup!

**Comment by yosaf055** [comment]
Ok

**Comment by anonymoussude** [comment]
@Aparus

**Comment by Aparus** [comment]
> @Aparus

what? :-) The issue is still actual for me.

**Comment by mlinksva** [comment]
@Aparus it looks like you're off to a good start in #1299. ✨ 

I added some clarifications to the translator documentation in #1482.
