### ISSUE TITLE
CONTRIBUTING.md is missing a "Contribution review process" section

### ISSUE THREAD

**Issue by Ludmila-N** [github/opensource.guide#1271]
https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md has a "Contribution review process" bullet in the Table of Contents, but no corresponding section in the body, or external link to describe the process.  
#contribution-review-process anchor does not point anywhere.
Please consider adding the review process description, or, worst case, removing the bullet from the Table of Contents. 
I could help removing the bullet, but have no knowledge of the review process, and hope you will be able to add the missing part.
Many thanks!!!

**Comment by mlinksva** [comment]
Looks like it was intentionally removed in https://github.com/github/opensource.guide/pull/596 but the ToC entry remains. Please do submit a PR removing the ToC entry @Ludmila-N. Thanks!

**Comment by suusha1340** [comment]
> https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md has a "Contribution review process" bullet in the Table of Contents, but no corresponding section in the body, or external link to describe the process.
> #contribution-review-process anchor does not point anywhere.
> Please consider adding the review process description, or, worst case, removing the bullet from the Table of Contents.
> I could help removing the bullet, but have no knowledge of the review process, and hope you will be able to add the missing part.
> Many thanks!!!
security-policy

**Comment by suusha1340** [comment]
https://www.contributor-covenant.org/
