### ISSUE TITLE
Add Bengali translation

### ISSUE THREAD

**Issue by nowshad-hasan** [github/opensource.guide#1294]
With approximately 228 million native speakers and another 37 million as second language speakers, Bengali is the fifth most-spoken native language and the seventh most spoken language by total number of speakers in the world. [Wiki](https://en.wikipedia.org/wiki/Bengali_language)
So, I've planned to translate the articles and guides in Bengali, my mother tongue.

**Comment by Aquinas1390** [comment]
CONTRIBUTING.md

**Comment by yanuar444** [comment]
terjemahan Indonesia bagaimana?

**Comment by nowshad-hasan** [comment]
No, it's Bangla, also called Bengali. Mostly used in Bangladesh and West Bengal (Kolkata), India.

**Comment by fuad021** [comment]
@nowshad-hasan, how's the translation going on? If possible, I wanna join as it's been ages but no progress record is found.

**Comment by mlinksva** [comment]
Feel free to open a pull request with work in progress at any time. Instructions at https://github.com/github/opensource.guide/blob/master/docs/translations.md

**Comment by fuad021** [comment]
@mlinksva If it overlaps with the work of @nowshad-hasan ? Isn't that be rude or something unappreciated in OSS community?

I'm totally new to this contribution thing.

**Comment by nowshad-hasan** [comment]
Hi @fuad021, It's a great pleasure to meet you. I opened this issue but couldn't manage to work on. And it's a big work to do. So, I think we can split up this work. You can translate these particular parts I've mentioned below:

- How to Contribute to Open Source
- Starting an Open Source Project
- Finding Users for Your Project
- Building Welcoming Communities
- Best Practices for Maintainers

 I'll do the rest and try my best to finish within this month.

**Comment by MikeMcQuaid** [comment]
Closing this in favour of a PR. Looking forward to it!
