### ISSUE TITLE
Welcoming Open Source Metrics Checker

### ISSUE THREAD

**Issue by umutphp** [github/opensource.guide#1307]
Many thanks to Github, maintainers and all the contributors for this great guide. 

I am very happy to contribute this project by translating it to Turkish. It also inspired me to make a checker tool to check if an open source project is contributor friendly or not. I just wanted to post the tool here to get some feedback about the idea and the tool. All kind of feedbacks and contributions are appreciated :). 

The project is [WOSPM/checker](https://github.com/WOSPM/checker).

**Comment by nathsmaR** [comment]
Col

**Comment by nathsmaR** [comment]
Bien

**Comment by Fradulentus** [comment]
Давай поговорим об идеи?В чем именно заключаеться твоей замысел?А что касается инструментов,то здесь и сейчас у нас есть все необходимое,за некоторым исключением.

**Comment by nathsmaR** [comment]
идеи, потому что у меня есть идея сделать программный продукт, который
может и способен блокировать любой алгоритм и в то же время просто иметь
возможность разблокировать их

**Comment by Fradulentus** [comment]
Скажи,а по какому именно принципу будет выстроен скелет твоего программного продукта ?Даже если допустить то,что тебе как разработчика удастся обойти ряд законов цифрового естества и заставить все внутренние,смежные а так же параллельно-потоковые функции существовать в пределах  абсолютного эффективного хаоса,то тогда назревает следующий вопрос.Зачем это нужно миру?Вопрос с подвохом.

**Comment by Fradulentus** [comment]
И вообще,что это за язык такой турецкий?Сейчас я вспомнил,как османская империя завоевывала берега одной лужи.Что это за помыслы такие воинственные?Чтобы рушить алгоритмы нужно бога слушать ритмы,что бог скажет,в то человек промажет.Извини если обидел.Пока пока.

**Comment by mlinksva** [comment]
Thanks @umutphp! I'm going to close and lock this as it seems to have attracted some off-topic comments. FWIW you might be interested in/find others interested in collaborating at https://chaoss.community/ (open source project health analytics).
