### ISSUE TITLE
Link invalid

### ISSUE THREAD

**Issue by zengjiajun0623** [github/opensource.guide#1416]
This link is invalid. Please take a look. 
https://news.realm.io/news/orta-therox-moving-to-oss-by-default/

![Lark20200219184144](https://user-images.githubusercontent.com/14859235/74827005-953fef00-5347-11ea-92aa-acd7b058be45.png)

**Comment by Felipe1198** [comment]
> This link is invalid. Please take a look.
> https://news.realm.io/news/orta-therox-moving-to-oss-by-default/
> 
> ![Lark20200219184144](https://user-images.githubusercontent.com/14859235/74827005-953fef00-5347-11ea-92aa-acd7b058be45.png)
