### ISSUE TITLE
Add CHAOSS as a resource or story to the Metrics guide

### ISSUE THREAD

**Issue by GeorgLink** [github/opensource.guide#1439]
Looking through https://opensource.guide/metrics/, I was wondering whether we could find a way to reference the [CHAOSS project](https://chaoss.community). CHAOSS is an open source project under the Linux Foundation that is focused on defining, standardizing, and implementing metrics so that anyone can start their metrics journey. CHAOSS recently released a [new version of metrics](https://chaoss.community/metrics) and provides a sophisticated tool [GrimoireLab](https://chaoss.github.io/grimoirelab). 

This might be too early, but I want to also mention it: Bitergia, the company behind GrimoireLab, is developing a SaaS metrics platform that is free to use for open source projects: [Cauldron.io](https://cauldron.io). Cauldron is in early alpha development and not stable to be recommended at the moment, but the people can use the tool as long as they know about the caveat.

_Disclaimer:_ I am a cofounder and colead of the CHAOSS project and I now work for Bitergia. This means I have my bias but am also well positioned to help with this kind of content.

I opened this issue to ask, whether adding CHAOSS, GrimoireLab, or Cauldron.io as a resource would be interesting for the [Metrics guide](https://opensource.guide/metrics/).

**Comment by nilli54** [comment]
#1439

**Comment by GeorgLink** [comment]
Hi @nilli54, What does it mean when you reference this issue within itself? I am not familiar with that practice. Thanks for helping me understand.

**Comment by mlinksva** [comment]
Hi @GeorgLink perhaps someone else [not associated](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md#ground-rules--expectations) with the projects will suggest adding one of the things that you've mentioned when they are beyond early alpha.

That said if you've got any broader thoughts or critiques about the metrics guide, I'd be interested in reading them. That guide is certainly the least developed and shortest of the guides, perhaps rightly so, as best practices aren't well established for OSS project metrics, at least not relative to topics covered in other guides.

**Comment by mlinksva** [comment]
> What does it mean when you reference this issue within itself?

It's pointless. I occasionally see new users do this, but I've no idea what leads them to do so, presumably they're just trying things out? 🤷‍♂

**Comment by MikeMcQuaid** [comment]
Closing this for now. We'd consider a PR from someone not associated with the project. Thanks!
