### ISSUE TITLE
Add a new guide on security

### ISSUE THREAD

**Issue by mayakacz** [github/opensource.guide#1486]
It would be nice to include content on security & keeping your open source project secure.

Content could help answer questions like:
- How can you track your dependencies & patch vulnerabilities?
- What should you do if you or a security researcher finds a vulnerability in your project?
- What can you do ahead of time to be best prepared to respond to a new vulnerability in your project?
- How can you review your project for security issues?
- At what stage/ maturity of your project does it make sense to more explicitly engage the security community? e.g., when to have a vulnerability reporting policy, a security team, a security review process, engage a third party for security review, launch a bug bounty program

**Comment by mlinksva** [comment]
I agree, would love to see this. A related prior effort was in #985.

**Comment by nilli54** [comment]
Thank you

**Comment by nilli54** [comment]
#1486

**Comment by nilli54** [comment]
> It would be nice to include content on security & keeping your open source project secure.
> 
> Content could help answer questions like:
> 
> * How can you track your dependencies & patch vulnerabilities?
> * What should you do if you or a security researcher finds a vulnerability in your project?
> * What can you do ahead of time to be best prepared to respond to a new vulnerability in your project?
> * How can you review your project for security issues?
> * At what stage/ maturity of your project does it make sense to more explicitly engage the security community? e.g., when to have a vulnerability reporting policy, a security team, a security review process, engage a third party for security review, launch a bug bounty program

**Comment by LooTKinGz** [comment]
File update

**Comment by np300** [comment]
> อัพเดตไฟล์

**Comment by MikeMcQuaid** [comment]
We'd review a pull request for this, thanks!
