### ISSUE TITLE
Can't load my activity feed

### ISSUE THREAD

**Issue by PriyanshuMay** [github/opensource.guide#1568]
from past few days I can't view my activity feed,
```
There was an error in loading the activity feed. Reload this page.
```

**Comment by eladkarako** [comment]
You are probably getting:

1. <code>Request URL: https://github.com/dashboard/recent-activity</code>: <code>401 Unauthorized</code>.
2. <code>Request URL: https://github.com/dashboard-feed</code>: <code>401 Unauthorized</code>.

lesser ones:
3. <code>Request URL: https://github.com/users/{your username}/feature_preview/indicator_check</code>: <code>404 Not Found</code>
4. <code>https://collector.githubapp.com/github/page_view?....</code>: <code>404 Not Found</code>

![2020-08-03_135835](https://user-images.githubusercontent.com/415238/89176469-494dd300-d592-11ea-8ad4-55fe5631c18c.png)

You might come to a conclusion that regardless of anything you unblock you connection is still forbidden, 
try use application in developer-panel to clear all storage and cookies and reloading.  

visit <code>chome://version</code> and see if there are any command-line switches you added or chrome added (by means of <code>chrome://flags</code>) that might mess things up.

I have Chromium and Chrome beta (side by side, different profiles, naturally..)
works in the Chrome beta, does not work in Chromium, 

not that bother me to say the truth, 
kind of useless notification no one cared about.

you can manually click the notification "bell" icon to see anything new. anyway....


happy debugging.

**Comment by MikeMcQuaid** [comment]
This repository is not for GitHub support. Contact them instead, thanks!
