### ISSUE TITLE
How to transfer ownership?

### ISSUE THREAD

**Issue by sospedra** [github/opensource.guide#1586]
Hello, really well done project.

Today I launched [rfm.sospedra.me](https://rfm.sospedra.me)
I'm looking for documentation to link **maintainers that are looking to transfer their projects**.
Do you cover this bit somewhere? I couldn't find it.

Thanks!

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words! Not sure if we cover this or not but it's not an issue with this project so closing this for now. Thanks again!
