### ISSUE TITLE
Some links/pages are broken

### ISSUE THREAD

**Issue by ericfennis** [github/opensource.guide#1609]
When I was reading some articles, I tried to open up some links but got the response: `nothing here`.

The broken links:

- https://opensource.guide/best-practices/
- https://opensource.guide/leadership-and-governance/
- https://opensource.guide/getting-paid/
- https://opensource.guide/code-of-conduct/

![image](https://user-images.githubusercontent.com/11825403/81324324-13827680-9097-11ea-9269-48677f08529d.png)

**Comment by quocbao38** [comment]
> When I was reading some articles, I tried to open up some links but got the response: `nothing here`.
> 
> The broken links:
> 
> * https://opensource.guide/best-practices/
> * https://opensource.guide/leadership-and-governance/
> * https://opensource.guide/getting-paid/
> * https://opensource.guide/code-of-conduct/
> 
> ![image](https://user-images.githubusercontent.com/11825403/81324324-13827680-9097-11ea-9269-48677f08529d.png)

**Comment by mlinksva** [comment]
The links work for me. `nothing here` isn't the error the site would typically return for a missing page; try https://opensource.guide/fjlfkjlsfadjfdls obtains

```
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.

GitHub Status — @githubstatus

```

If you encounter this again and can provide any more information, please do.
