### ISSUE TITLE
Bug in GitHub website: Follow button in sticky navbar not in sync with profile

### ISSUE THREAD

**Issue by cseas** [github/opensource.guide#1630]
**Steps to reproduce the bug:**
1. Visit someone's profile on GitHub and press the "Follow" button below their profile photo.
2. Scroll down so the sticky navbar appears.
3. The sticky navbar still shows the "Follow" button even though you've already followed the person.

**Expected behaviour:**
The "Follow" button in the sticky navbar should show as "Unfollow". It seems the button is either not in sync or not refreshed when you click the main "Follow" button on someone's profile.

P.s. This is the closest repository I could find for reporting this bug so pardon me if I landed at the wrong place. Really disappointed to see the GitHub organization doesn't have any repository even remotely related to reporting non-security bugs or getting community feedback about the GitHub website itself.

**Comment by MikeMcQuaid** [comment]
This repository is not for filing issues for GitHub. Please use https://support.github.com/contact
