### ISSUE TITLE
Accessibility for non-English speakers

### ISSUE THREAD

**Issue by chrisgraham** [github/opensource.guide#1634]
Hi there,

There are a lot of de facto standards around standard docs files for a project (README, CODE_OF_CONDUCT, etc).

The best source for listing these standards I could find is Wikipedia (https://en.wikipedia.org/wiki/README). The best source I could find for discussions on them is here and the GitHub documentation. [off-topic, but if there is some project trying to bring all this together other than the GitHub documentation I'd love to know].

GitHub and other tools then recognize these standards.

One things that concerns me though is that there's probably a built in assumption of them being uni-language here. In reality, that usually means English.

Should we be promoting some kind of standard for Internationalisation? For example, recognizing docs/FR/README.md and then tools like GitHub could be serving French users automatically?

People would be able to create pull requests to add translations of course.

Whilst most programmers learn English to a good level, that's definitely not universal in my experience. I've had many people struggle to communicate in English and talk about creating non-English support communities.

I feel the standards we promote should to some degree serve the needs of these users.

**Comment by MikeMcQuaid** [comment]
Hi @chrisgraham! Good feedback but this doesn't seem to be specific/actionable based on the current open source.guide content so closing this out for now. Thanks!
