### ISSUE TITLE
Setting expectations for user rights and responsibilities

### ISSUE THREAD

**Issue by chrisgraham** [github/opensource.guide#1635]
I think it is great that we now have a broad consensus on things like codes of conducts and contributor documentation.

However, from a user point of view, I think we have some way to go to provide effective and standardized communication on what rights and responsibilities users have.

Some projects may be hacker communities where people are expected to provide their own solutions to problems. Other projects are professionally run and seek to provide reliable support to users. Most projects will be somewhere in-between and often it's not immediately clear what a project is.

People get into arguments about what it reasonable for them to expect and for what others to expect for them. For example, is fixing critical bugs a responsibility of the users affected by the bugs, or of a maintainer? What is a critical bug even? Can users expect no support, an offer of a commercial support arrangement, or free support - and to what degree? What kind of security fix guarantees may be given?

Users who are not themselves programmers with the capability to "self start" on things need answers to these questions if they are going to be able to move forward in a reliable way without tempers getting frayed.

To that end, I think standardizing this would be excellent for community cohesion. People get on a lot better when everyone is on the same page from the start.

There exists some de facto use of a 'SUPPORT' file already. Perhaps we can document what should go in there? And then specifics about how to contribute continue to go into a 'CONTRIBUTING' file?

**Comment by MikeMcQuaid** [comment]
Hi @chrisgraham! Good feedback but this doesn't seem to be specific/actionable based on the current open source.guide content so closing this out for now. Thanks!

**Comment by chrisgraham** [comment]
The purpose would be to expand the guide to cover what IMO is an important topic. I might even contribute to doing that, but think a discussion is important first. If this isn't a good place to do that, could you suggest a place that is?

**Comment by MikeMcQuaid** [comment]
We're not really updating content beyond fixing errors and blatant omissions due to things changing since writing. I'm afraid this doesn't fit under that. I'd suggest creating your own guide/document/blog post about this and posting it here so anyone interested can find it. Thanks!
