### ISSUE TITLE
Create a release process

### ISSUE THREAD

**Issue by edumco** [github/opensource.guide#1712]
I would be nice to have a release process so we could be notified whenever a new version is released.

The release would bring several advantages:

1. Readers could be notified on changes

2. Translators could be notified when new content need translations

3. It is faster and easier to review only the diffs than read the whole documentation looking for problems.

4. It is easier to create clear roadmaps and issues and follow the changes. 

The process can be automated using Github Actions

**Comment by jamesedmondsmith1** [comment]
Up user name james edmond smith.

jes

**Comment by marknguyen92** [comment]
> I would be nice to have a release process so we could be notified whenever a new version is released.
> 
> The release would bring several advantages:
> 
> 1. Readers could be notified on changes
> 2. Translators could be notified when new content need translations
> 3. It is faster and easier to review only the diffs than read the whole documentation looking for problems.
> 4. It is easier to create clear roadmaps and issues and follow the changes.
> 
> The process can be automated using Github Actions

**Comment by MikeMcQuaid** [comment]
Let's roll this into https://github.com/github/opensource.guide/issues/1119. I'm interested in accepting contributions to do something like this but I don't know how (and don't have time myself). Thanks!
