### ISSUE TITLE
dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [github/opensource.guide#1722]
Please do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by MaivKhanhPr0** [comment]
[]()

**Comment by yufi1213** [comment]
> Please do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme



> Please do not ignore this property of useragent https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by MikeMcQuaid** [comment]
This is out of scope as it will be a lot of work and most sites do not respect this.
