### ISSUE TITLE
How to use third party opensource software

### ISSUE THREAD

**Issue by peteruithoven** [github/opensource.guide#1761]
I'm not sure if this is the right place to ask, but information on what to do when you want to include third party opensource software. At least software released under common licenses like MIT, Apache etc. How you should for example include license and copyright notices. Maybe include some good examples. 

A quick search gave me these examples:
- [Facebook](https://www.facebook.com/legal/740956232671531)
- [Commvault](https://documentation.commvault.com/commvault/v11/article?p=50068.htm)
- [Volkswagen](https://connect.volkswagen-we.com/index/legal/third-party-license-notices.html)
- [Altova](https://www.altova.com/legal/3rdparty)
- [hangfire.io](https://www.hangfire.io/licensing/third-party.html)
- [Figma](https://www.figma.com/open-source/)
- [Microsoft Edge](https://www.microsoft.com/en-us/legal/products/notices/msedge)
- [Spotify](https://developer.spotify.com/legal/third-party-licenses/)

Possibly relevant resources:
- https://opensource.stackexchange.com/questions/7307/what-is-the-appropriate-way-to-include-third-party-libraries-copyright-notice-an
- [Easy Attribution Document Generator](https://tldrlegal.com/generate)
- https://www.smartcopying.edu.au/open-education/creative-commons/creative-commons-information-pack-for-teachers-and-students/how-to-label-third-party-content-in-creative-commons-licensed-material
- https://softwareengineering.stackexchange.com/questions/188152/do-i-have-to-include-the-license-of-a-third-party-library-imported-as-a-dll
- https://opensource.stackexchange.com/questions/6081/i-am-using-a-mit-licensed-module-in-a-closed-source-consumer-device-what-are-my

**Comment by MikeMcQuaid** [comment]
Sorry, this is out of scope for this repository.

**Comment by peteruithoven** [comment]
Is there a more appropriate place for these kind of suggestions? 

Again, it makes no sense there is so little information on this. This site contains info on contributing to, getting paid for, but not how to legally use it...

**Comment by mlinksva** [comment]
This is similar to #1084 and like I said there, I could see adding a brief section to the legal guide, but no promises as to when. Sharing relevant resources as you did in the issue comment is a great way to contribute, feel free to add more.

**Comment by peteruithoven** [comment]
Thanks @mlinksva. 

Small update, for now we're probably going to try using this package:
https://github.com/codepunkt/webpack-license-plugin
This will generate a json file with license info for all the packages that are used in the build. Information like the name, author, license, licenseText etc. 

For me one aspect that is unclear if I really enough to only include copyright notices for the software I'm deploying.

**Comment by peteruithoven** [comment]
A bit more on the selection from the package's author: https://github.com/codepunkt/webpack-license-plugin/issues/400#issuecomment-687347341
