### ISSUE TITLE
Missing how to tackle a large code base

### ISSUE THREAD

**Issue by Mandroide** [github/opensource.guide#1763]
I am suggesting to add a section about how to tackle a large code base in an open source project .

I see that is pretty common that someone doesn't know how to tackle a large code base. Besides reading the documentation (which might be outdated sometimes), they might not be aware of some tools to use (like grep or source explorer software), aren't like an user expert of the software before hand or maybe don't try to create some tests to see if they can grasp how it works.

**Comment by MikeMcQuaid** [comment]
Sorry, we're not adding new guides at this time.
