### ISSUE TITLE
XCsoar V 7.00 on linux  Flarm Screen zoom

### ISSUE THREAD

**Issue by Icthosib** [github/opensource.guide#1797]
I am running xcsoar Version 7 on an Openvario  with rotary and button inputs (no touch screen). On the Flarm page the rotary page does not zoom in or out but switches to another page.  On all the other map pages the rotary zooms in and out. It is therefore impossible to change the zoom on the flarm page to anything other than the zoom of 500m

**Comment by passgit713** [comment]
Pull request bug``

**Comment by passgit713** [comment]
Pull request
