### ISSUE TITLE
Create a community moderation guide

### ISSUE THREAD

**Issue by nayafia** [github/opensource.guide#180]
@lee-dohm opening this issue so I don't forget. I would *love* if you wrote a community moderation mini-guide!

Right now most of the guides are 3-10 pages in a GDoc. Happy to talk through more if it's of interest. The timing is totally flexible (we're launching the first set in a few weeks, but can add new ones whenever). I think it would be a really valuable addition. :pray:

**Comment by kytrinyx** [comment]
Adding Lee's community manager curriculum as a resource: https://github.com/lee-dohm/community-manager
