### ISSUE TITLE
Iptv link arbic

### ISSUE THREAD

**Issue by toomoon1979** [github/opensource.guide#1809]
I need m3u for arbic

**Comment by AlgaedAhmed** [comment]
_[](https://github.com/github/opensource.guide/issues/1809#issue-705047161)_

**Comment by AlgaedAhmed** [comment]
> I need m3u for arbic 

[]()

**Comment by toomoon1979** [comment]
Can you help me to watch iptv for word Chanel. If any one can get me how can download iptv m3u link Iam very thankful for get me that . 
Regarding your

**Comment by JACKMESON** [comment]
Oh I just saw your email [[]()]()

**Comment by AlgaedAhmed** [comment]
‫أُرسلت من الـ iPhone‬

**Comment by toomoon1979** [comment]
Any one can give m3u working for arbic and English Channel . 
Regarding please please[]()

**Comment by HugoDespoix** [comment]
Idem on smart tv samsung  cencured porn and sex Channel if You dont pay Passionxxxtv
