### ISSUE TITLE
Linking RedHat's Open Source Participation Guidelines

### ISSUE THREAD

**Issue by webknjaz** [github/opensource.guide#1905]
Hi, RedHat's Open Source Participation Guidelines just got out. See https://red.ht/31a60wB / https://www.redhat.com/en/about/open-source/participation-guidelines / https://www.redhat.com/en/resources/open-source-participation-guidelines-overview.

I think it may be useful to have a link pointing there. Although, I don't clearly see where it'd fit best so I'm not sending any PRs. It's up to the maintainers to decide if it's worth it.

**Comment by vantuan1994** [comment]
#437

**Comment by romara20** [comment]
Thats better

**Comment by Jayson29-undroid** [comment]
nice and better

**Comment by Ghermezgraphic98** [comment]
#1800

**Comment by rtrtrt777** [comment]
> Hi, RedHat's Open Source Participation Guidelines just got out. See https://red.ht/31a60wB / https://www.redhat.com/en/about/open-source/participation-guidelines / https://www.redhat.com/en/resources/open-source-participation-guidelines-overview.
> 
> I think it may be useful to have a link pointing there. Although, I don't clearly see where it'd fit best so I'm not sending any PRs. It's up to the maintainers to decide if it's worth it.

**Comment by lam19892089** [comment]
> Xin chào, Nguyên tắc tham gia nguồn mở của RedHat vừa được công bố. Xem https://red.ht/31a60wB / https://www.redhat.com/en/about/open-source/participation-guidelines / [https://www.redhat.com/en/resources/open-source -participation-hướng dẫn-tổng quan](https://www.redhat.com/en/resources/open-source-participation-guidelines-overview) .
> 
> Tôi nghĩ rằng nó có thể hữu ích nếu có một liên kết trỏ đến đó. Mặc dù, tôi không thấy rõ nơi nào phù hợp nhất nên tôi sẽ không gửi bất kỳ bài PR nào. Người bảo trì quyết định xem nó có xứng đáng hay không.

**Comment by napmhae** [comment]
Great

**Comment by MikeMcQuaid** [comment]
> Although, I don't clearly see where it'd fit best so I'm not sending any PRs. It's up to the maintainers to decide if it's worth it.

Thanks for the heads up but passing on this!
