### ISSUE TITLE
Author:pass713 pull request

### ISSUE THREAD

**Issue by afshin2020** [github/opensource.guide#1919]
Author:pass713 pull request

_Originally posted by @passgit713 in https://github.com/github/opensource.guide/pull/1800#issuecomment-695295233_

**Comment by Elvistcb** [comment]
> Author:pass713 pull request
> 
> _Originally posted by @passgit713 in [#1800 (comment)](https://github.com/github/opensource.guide/pull/1800#issuecomment-695295233)_
Tcb
