### ISSUE TITLE
https://github.com/ruby/TryRuby/blob/84ec432786e9f38dc27477f974583d6a7710be30/source/try_ruby_en.json#L41

### ISSUE THREAD

**Issue by Budda0ne** [github/opensource.guide#2007]
https://github.com/ruby/TryRuby/blob/84ec432786e9f38dc27477f974583d6a7710be30/source/try_ruby_en.json#L41

The text in this lesson is asking the user to find the number of plays Shakespeare wrote in 1591 using the `count_plays` method, but in the example code, `count_plays` is called with a `year` value of 0. As a result the code errors if not modified.

The last line of the example code should read as follows:
```ruby
puts count_plays(1591)
```

If nobody else beats me to it, I'll gladly open a PR for this when I have a bit more time.

__Originally posted by @skylarmacdonald in https://github.com/ruby/TryRuby/issues/85__

**Comment by SaavyGirl** [comment]
Looks good.[]()
