### ISSUE TITLE
Problem when switching between languages

### ISSUE THREAD

**Issue by thomasbaydev** [github/opensource.guide#2022]
Hello opensource.guide Team,

Just an info about the change between languages on the website.
There is a problem when switching from English to Other language for articles in the format \/[a-z]+([_-][a-z]+)?\/. They match with the regex of the redirect function.

Hoping to help!
Thomas

**Comment by mlinksva** [comment]
I cannot reproduce a language switching problem. If this still exists, please give a concrete example of which page(s) demonstrate the issue.
