### ISSUE TITLE
Portuguese translation for the phrase "You dit it!"

### ISSUE THREAD

**Issue by gabrielsanttana** [github/opensource.guide#2023]
## Context:

The portuguese version of the [Open Source Guide](https://opensource.guide/pt/how-to-contribute/) on how to contribute has the translation _"Você fez isso!"_ for the phrase _"You did it"_, which is not the most correct or common translation for this specific ocasion, since it is actually being translated in a strict way.

## Possible change:

A more appropriate translation for this phrase would be _"Você conseguiu!"_, which is a more semantic one and also the one we use the most.

**Comment by deniseyu** [comment]
Hey @gabrielsanttana, thanks for this feedback! We'd definitely welcome a PR to change this, if you are up for it 😄

**Comment by gabrielsanttana** [comment]
@deniseyu Definitely! I'll link it up here 😄
