### ISSUE TITLE
Hey everyone. Nice to meet you all. I'll see where I can jump in, but looks like @casals is on a roll!

### ISSUE THREAD

**Issue by Dino1981** [github/opensource.guide#2042]
Hey everyone. Nice to meet you all. I'll see where I can jump in, but looks like @casals is on a roll!

_Originally posted by @MishManners in https://github.com/github/docs/discussions/116#discussioncomment-93073_

**Comment by saeidasade123** [comment]
از آشنایی با همه خوشبختم من دنبال پروژه لزرگی هستم که بتوانیم پول را به معنی واقعی یکی کنیم و بتوانیم در هر جای دنیا که باشیم با پولی که داریم استفاده کنیم منظورم پول کل کره خاکی یکی باشد آن هم پول الکترونیکی، میخواهم دست به دست هم بدهیم و این پروژه رو بسازیم میدونیم که میتونیم  بله ما میتونیم از کسی که به من ایمیل داد خواهشا خصوصی 
به من ایمیل بدهد تا بگویم چه کاری انجام دهیم ممنون
We can unite money in the real sense and we can use the money we have wherever we are in the world. I mean the money of the whole planet is the same as electronic money. I want to join hands and build this project. We know that we can. Yes, we can.  We can ask the person who emailed me a private email to tell me what to do. Thank you.

**Comment by saeidasade123** [comment]
هر کی حاضره بیاد جلو ایمیل من saeidasade1234@gmail.com هستش

**Comment by Dino1981** [comment]
#2073
