### ISSUE TITLE
Is 'SourceSort.com' project still alive? It's in 'Finding a project to contribute to' section, but the link is dead

### ISSUE THREAD

**Issue by manvydasu** [github/opensource.guide#2079]
I checked it in http://web.archive.org/. The last time it was crawled was in Octorber.

**Comment by ngothanhthai** [comment]
> I checked it in http://web.archive.org/. The last time it was crawled was in Octorber.

**Comment by deniseyu** [comment]
Oops, apologies for closing out - @manvydasu if it does not appear to be active anymore, we'd welcome a PR to remove that from the list of projects!
