### ISSUE TITLE
failed to push some refs #1

### ISSUE THREAD

**Issue by ramakrishnakommineni245** [github/opensource.guide#2099]
I have an error while pushing or updating my local files into the remote
I have tried git push -u origin main and git push origin master --force
I got error: src refspec main does not match any
error: failed to push some refs to 'https://github.com/ramakrishnakommineni245/devproject.gi
t'

**Comment by thetoom001** [comment]
https://github.com/github/opensource.guide/issues/2099#issue-779627148
