### ISSUE TITLE
A26

### ISSUE THREAD

**Issue by krebsyba** [github/opensource.guide#2110]

**Comment by ngothanhthai** [comment]
https://github.com/github/opensource.guide/issues/2110#issue-782667817

**Comment by taska1217** [comment]
Ok

**Comment by taska1217** [comment]
Jo

**Comment by taska1217** [comment]
Ok

**Comment by taska1217** [comment]
Jo

**Comment by zainuji** [comment]
Someone hack my email through bigo app

**Comment by zainuji** [comment]
How to secure when m scanned my email id then showing there sawn app
