### ISSUE TITLE
Spelling display error

### ISSUE THREAD

**Issue by suryaanshah** [github/opensource.guide#2116]
**Website**: [https://opensource.guide/leadership-and-governance/](https://opensource.guide/leadership-and-governance/)
**Browser**: Mozilla Firefox
**Bug**: Title looks misspelled.
![image](https://user-images.githubusercontent.com/47082682/104332237-f9e2da00-5515-11eb-98ad-d2d8e2728566.png)
However when we copy this text, the spelling is correct.

**Comment by mlinksva** [comment]
Similar was reported once before, in #1204 but there the characters were missing in Chrome. Like then, I can't reproduce this in any browser.

If anyone has an idea as to how this could happen, but only very rarely, please share!

**Comment by suryaanshah** [comment]
@mlinksva Thankyou for looking into this!
I read #1204 and I think this is the same problem. I used Google Translate to check if the same problem is occurring in other languages too.
It turns out it is happening in almost all the languages. For example Romanian:
![image](https://user-images.githubusercontent.com/47082682/107643606-60d1eb00-6c9c-11eb-8f3f-561e2a51e188.png)
![image](https://user-images.githubusercontent.com/47082682/107643659-747d5180-6c9c-11eb-8f2f-9f1d118415aa.png)

I notice that, in all the languages, the hidden/misspelled alphabets fall under the same column.
From this observation, I suspect there is blank column added on the web-page which is over-laping the alphabet making the heading looks misspelled.

**Comment by suryaanshah** [comment]
I notice another thing, but I am not sure if it is very right. In #1204 also, the letter 'r' was missing. I notice that in the 'Governance' the letter 'r' is missing and in Romanian also, the letter 'r' is missing. Maybe there is a function written in the code which hides the letter 'r' from the heading.
