### ISSUE TITLE
Hello from the GitHub Docs team! @gracevor here.

### ISSUE THREAD

**Issue by hk12110** [github/opensource.guide#2194]
Hello from the GitHub Docs team! @gracevor here.

We’re looking to learn more about your experience with [GitHub Docs](https://docs.github.com/en) and will be holding feedback sessions next week, January 25-27. These will be one-hour interview sessions, and we'll provide you with a gratuity as a thank you for your time!

Qualifications:
* Must be a GitHub user (beginners are welcome!)
* Must have used [GitHub Docs](https://docs.github.com/en) in the past two weeks

To participate, fill out our quick survey [here](https://www.surveymonkey.com/r/8M3GSJB). We’ll reach out if you’re a fit for the study. Thank you!

_Originally posted by @gracevor in https://github.com/github/docs/discussions/3005_

**Comment by Derar1986** [comment]
@Close GitHub

**Comment by devifeoma** [comment]
Hi *@gracevor <https://github.com/gracevor>,*

*I’m getting this error while trying to take the survey *
[image: Screenshot 2021-02-12 at 08.03.27.png]

**Comment by gracevor** [comment]
Thanks @devifeoma - this project has ended, I'll close this discussion. We'll post again when we have a new study going on. Thank you!
