### ISSUE TITLE
Wrb

### ISSUE THREAD

**Issue by koosy79** [github/opensource.guide#2214]

**Comment by Pesho8505** [comment]
🤷🏼‍♂️

**Comment by apsiriwat** [comment]
> 🤷🏼‍♂️



> _No description provided._

**Comment by habibahma** [comment]
I'm glad you asked! Many people come to GitHub because they want to contribute to open source 📖 projects, or they're invited by teammates or classmates who use it for their projects. Why do people use GitHub for these projects?

**Comment by walli55** [comment]
pphub://user?login=
