### ISSUE TITLE
github:master

### ISSUE THREAD

**Issue by hainusii** [github/opensource.guide#2270]
[![Coverage Status](https://coveralls.io/builds/14571945/badge)](https://coveralls.io/builds/14571945)

Coverage decreased (-0.5%) to 98.598% when pulling **62c3fb99c52c97f723a150ee260eabb29b44e027 on cdwort:support_error_comparison** into **25be7a23ffb583adaf9a0bf9b03754b114f0be11 on github:master**.

_Originally posted by @coveralls in https://github.com/github/scientist/issues/77#issuecomment-350358185_

**Comment by maisoenaingtun** [comment]
{{#2270}}
