### ISSUE TITLE
[]()![chrome_qrcode_1615829362535.png](https://user-images.githubusercontent.com/65473516/111229986-1bd30880-85fc-11eb-9c0f-f4765aba14af.png)

### ISSUE THREAD

**Issue by Amirnateghi1** [github/opensource.guide#2271]
[]()![chrome_qrcode_1615829362535.png](https://user-images.githubusercontent.com/65473516/111229986-1bd30880-85fc-11eb-9c0f-f4765aba14af.png)

_Originally posted by @Amirnateghi1 in https://github.com/coollog/micronaut-jib/pull/1#issuecomment-799800717_

**Comment by Brylon1994** [comment]
@technicalpickles

**Comment by 556677152** [comment]
https://github.com/github/opensource.guide/issues/2271#issuecomment-799810156

**Comment by minhtri15** [comment]
> ![chrome_qrcode_1615829362535.png](https://user-images.githubusercontent.com/65473516/111229986-1bd30880-85fc-11eb-9c0f-f4765aba14af.png)
> 
> _Originally posted by @Amirnateghi1 in [coollog/micronaut-jib#1 (comment)](https://github.com/coollog/micronaut-jib/pull/1#issuecomment-799800717)_

**Comment by maisoenaingtun** [comment]
#2271

**Comment by Thiwach** [comment]
เหตุและผลโต้แย้งได้หรือไม
การที่ต้องต้องการแหล่งเงินทุนเพื่อจดทะเบียนการทำธุระกิจ
,จัดจ้างนักศึกษาด้านITมาช่วยงานชั่วคราว
,หาคอมพิวเตอร์มือ2มาใช้ทำงานสะดวกกว่านั่งพิมพ์ในโทรศัพ์มาเกือบ4เดือน,ผลดีเชิงบวกสถานศึกษาที่ผมติดตอหานักเรียนเรียนดีแต่ขาดทุนทรัพย์มาช่วยงานเพื่อนักษาจะได้มีรายได้ระหว่างเรียน,ก่อนที่Facebook จะยกเลิกการใช้งาน Facebook pay ในอีก2เดืวันข้างหน้า ,Facebook   เปิดโอกาสสนับสนุนทุนเริ่มต้นเล็กน้อยทุนที่Facebook ระดมมาให้จะแยกออกไว้เพื่อสนัชุดนักเรียน,ที่สุดการที่จ้างนักเรียน,เป็นการโปรโมทแบรนด์ ของเรานักเรียนเกือบ5000คน เราอาจจะใช้เทคนิคพิเศษ เช่น
รับสมัครโดย ทดสอบ ทักษะ ในการใช้software  คนที่เก่ง2ด้าน
Hardwareกัsoftware เราก็เปิดรับซ่อมคอมพิวเตอร์ ในราคาพิเศษ กำไรเก็บแยกส่วน จึงต้องจ้างนักศึกษาด้านการตลาด
ช่วยแบ่งเบางานของผม,คอมฯที่บ้านผมบริจาคให้โรงเรียนไปแล้วจึงทำงานช้าเนื่องจาก ใช้งานบนโทรศัพท์   ***ตั้งมี่ส่วนร่วมกัGoogle  githubเป็นเพื่อนแท้***  ขอความช่วยเหลือ ไป94วันไม่เคยได้การตอบรับที่ดีรู้สึกโดดเดี่ยวท้อแท้   แต่น้ำใจของgithubทำให้ผมสู้ต่อ ยอมอดกินข้าว เก็บเงินไว้ใช้งานจ่านค่าอินเตอร์เน็ต
ค่าบริการโทรศัพท์

**Comment by Thiwach** [comment]
คุณทราบไหมว่าผมเคยเป็นครูสอนคอมพิวเตอร์

**Comment by Thiwach** [comment]
พื้นฐานความถูกต้องกับจริยธรรมของความเป็นครู 
เพื่อช่วยเหลือนักเรียน ครูยอมโดนด่า เพื่อช่วยนักเรียน
1ใน10วิชาครูจริยธรรม+คุณธรรม
***เอกสารรับรองเงินเดือน6เดือนจากgithub มิต้องค้ำประกันใดๆ***

**Comment by Thiwach** [comment]
ราตรีสวสดิ์คร้บ

**Comment by luismedicina23** [comment]
Em dom., 21 de mar. de 2021 às 16:40, Thiwach ***@***.***>
escreveu:

**Comment by luismedicina23** [comment]
Ary

Em dom., 21 de mar. de 2021 às 16:40, Thiwach ***@***.***>
escreveu:

**Comment by luismedicina23** [comment]
Im insubs

Em dom., 21 de mar. de 2021 às 16:40, Thiwach ***@***.***>
escreveu:
