### ISSUE TITLE
Do not give up after one ping

### ISSUE THREAD

**Issue by plainerman** [github/opensource.guide#2275]
I would like to discuss how to properly handle cases where a project is actively maintained and accepts external contributions but one still can't get an answer (I have been there). For example, when a specific maintainer is on a longer time off.

Specifically, the discussion should be regarding [this section](https://opensource.guide/how-to-contribute/#-you-dont-get-a-response) in this file

https://github.com/github/opensource.guide/blob/19d5f7bae240d8632595758345632e6cdbb45b76/_articles/how-to-contribute.md#L306-L312

It sounds to me like one should "give up" after a single ping. Especially for PRs where a lot of time has been put into, I suggest to not give up so quickly. I would like to discuss with you a proper way to handle such cases so that the page can be improved.

Two things come to my mind that could be included in this section before saying to "give up":

- State that you can politely try again the ping the assignee. For this it would be important to also state that the ping interval should be increased (e.g. wait a month before the next ping)
- If the project has other active maintainers, try to mention them and ask whether they can help

I believe that we should adapt this part to create a more complete resource.

Do you have any other (better) ideas or further suggestions for such cases?

**Comment by CuneytMutlu** [comment]
biraz heyecanlıyım bu konuda uykusuzum kendimi çok yorgunum ama ada için değer isterseniz söyle yapalım benim hesaptan oyunu oynata biliyorsanız oynatın ben sadice seyredeyim bir süre hem daha net görmüs olurum

**Comment by csb2890** [comment]
Colleen Bainbridge
________________________________

**Comment by arjunnarang** [comment]
I looked into the issue suggested by you @plainerman and I think we can improve it by giving some confidence to others. I'm stating certain ideas here so I request you to have a look at them below:-

-->Pinging the assignee at a certain interval of time. It does not guarantee the response from the assignee but it does guarantee that the assignee would remember the contributor's name if the contributor further makes any amendments in the project as he was very professional and polite in the first place...

-->Stating that even after some pings, the assignee is not responding to the contributor then it does not mean that the contributor has wasted his or her time, it simply means the contributor has gained some experience in this field comparing to those who haven't even started. EXPERIENCE MATTERS EVERYWHERE!!

-->Always keep going and learning from past experience and stating that, "It is either success or learning but there is nothing such as failure". 

You can then state to move on to a new project. Hope this helps..

**Comment by loida24** [comment]
You don't get a response.

**Comment by loida24** [comment]
Thanks

**Comment by mlinksva** [comment]
Personally, I feel the current text strikes the right balance (which includes brevity and simplicity), particularly for first time contributors. Yes, if a change is really important, further pings might be OK at an increasing interval. So would maintaining a fork with the important change. But most changes aren't like that. If someone else thinks the change is interesting, they'll notice it.

**Comment by shanevz** [comment]
Sho

**Comment by MikeMcQuaid** [comment]
> Personally, I feel the current text strikes the right balance (which includes brevity and simplicity), particularly for first time contributors

Agreed. Passing on this change, sorry!
