### ISSUE TITLE
GitHub app's featured repositories 

### ISSUE THREAD

**Issue by mahrud** [github/opensource.guide#2293]
If this isn't the right place for this issue, I apologize, but I assumed this repository also serves as GitHub's own code of conduct.

Today on GitHub's android app under the "Explore" tap the following repository was featured:
<img src="https://user-images.githubusercontent.com/3147718/112765817-8f015500-8fd4-11eb-9c1b-d7d127b859ce.png" alt="Screenshot_20210328-144312~2" style="max-width:100%;" width=250px>

Given the number of GitHub employees who have signed the [open letter](https://rms-open-letter.github.io/) calling for the removal of RMS, I would have hoped to see GitHub among the organizations calling for removal of RMS. However, featuring this repository indicates a tacit support for RMS by GitHub.

I don't think the actions and words of this individual are compatible with your [Contributor Covenant Code of Conduct](https://github.com/github/opensource.guide/blob/main/CODE_OF_CONDUCT.md), so I was hoping you could exclude it from the Explore tab.

**Comment by mahrud** [comment]
This seems to be listed on the [Explore](https://github.com/explore) page as well:
<img src="https://user-images.githubusercontent.com/3147718/112767210-02a66080-8fdb-11eb-95e5-9c784b16b25d.png" alt="image" width="250px">

@Oneill38 I tried opening an issue in the [github/explore](https://github.com/github/explore) repository but that wasn't an option, and I'm not sure how to open a pull request to exclude a particular repository from trending. Hope this isn't an inappropriate way to raise this issue.

**Comment by bdougie** [comment]
Hey @mahrud. Thanks for opening this issue. Our support team is better equipped to handle this request.

https://github.com/support

**Comment by mahrud** [comment]
Thanks for the suggestion! I attempted that before making this issue by clicking on "Reporting abuse or spam" and then clicking ["Report content"](https://support.github.com/contact/report-abuse?category=report-content&report=other&report_type=unspecified), but when I filled the form and click submit I get the following error:

![image](https://user-images.githubusercontent.com/3147718/112770903-a51c0f00-8fee-11eb-9211-412c725a5e27.png)

Now I opened a ticker by reporting the `rms-support-letter` org, but I don't expect GitHub to remove the org and the Explore page doesn't have its own report button.

Sorry if I missed a clearer route to reporting this matter.

**Comment by martinwoodward** [comment]
Thanks @mahrud - reported the regarding trending repos to our community support folks.

Confusingly, the contribution guidelines for the explore page refers to the collections and topics in that repo and not the algorithmic content such as the trending repos on GitHub.  At the moment it doesn't look like we have a good way for someone to report unwanted content in the list they are presented - we'll take a look at that.

Thanks again for making the effort to reach out - appreciate it.
