### ISSUE TITLE
This seems to be listed on the [Explore](https://github.com/explore) page as well:

### ISSUE THREAD

**Issue by alirezaebiii** [github/opensource.guide#2294]
This seems to be listed on the [Explore](https://github.com/explore) page as well:
<img src="https://user-images.githubusercontent.com/3147718/112767210-02a66080-8fdb-11eb-95e5-9c784b16b25d.png" alt="image" width="250px">

In particular, the [contributing guide](https://github.com/github/explore/blob/main/CONTRIBUTING.md) for [github/explore](https://github.com/github/explore) includes:
> Please note that all suggestions must adhere to GitHub's [Community Guidelines](https://help.github.com/articles/github-community-guidelines/) and [Terms of Service](https://help.github.com/articles/github-terms-of-service/). Per our Terms of Service, [you are responsible](https://help.github.com/articles/github-terms-of-service/#d-user-generated-content) for the content you contribute, and you must have the rights to use it.

@Oneill38 I tried opening an issue in that repository but that wasn't an option, and I'm not sure how to open a pull request to exclude a particular repository from trending. Hope this isn't an inappropriate way to raise this issue.

_Originally posted by @mahrud in https://github.com/github/opensource.guide/issues/2293#issuecomment-808955451_

**Comment by mahrud** [comment]
@alirezaebiii I think you opened this duplicate by accident. Could you remove it? I don't mean to cause any harassment.

**Comment by deniseyu** [comment]
Thanks @alirezaebiii, we've addressed this for github/explore!
