### ISSUE TITLE
> A configuration change would be something outside of our code that we change with our production environment, such as environment variables, virtual machine tier or quantity, or service providers.

### ISSUE THREAD

**Issue by nerminaali81** [github/opensource.guide#2313]
> A configuration change would be something outside of our code that we change with our production environment, such as environment variables, virtual machine tier or quantity, or service providers.
> 
> * _Primary person_:
> * _Second person_:
> * _When_:
> * _Zoom URL_:
> 
> ### What is the configuration change?
> ### Why are we updating this configuration?
> ### What risks are there with this configuration change?
> ### If an issue happens, how do we roll back?
> Once the change is verified good, please close this issue.

Ok

_Originally posted by @nerminaali81 in https://github.com/github/docs/issues/5030#issuecomment-813446356_

**Comment by Co0olboi** [comment]
``

**Comment by Co0olboi** [comment]
Brownawolf@gmail.com
