### ISSUE TITLE
I WILL RESOLVE THIS ISSUE

### ISSUE THREAD

**Issue by Art198** [github/opensource.guide#2317]
I WILL RESOLVE THIS ISSUE

_Originally posted by @rushi-12320 in https://github.com/github/opensource.guide/issues/2299#issuecomment-812883232_

**Comment by alirezaebiii** [comment]
> I WILL RESOLVE THIS ISSUE
> 
> _Originally posted by @rushi-12320 in [#2299 (comment)](https://github.com/github/opensource.guide/pull/2299#issuecomment-812883232)_
