### ISSUE TITLE
Link to Pages version of contributing file

### ISSUE THREAD

**Issue by benbalter** [github/opensource.guide#237]
It's a bit jarring to click a link on the navbar of opensource.guide and land on an anchor on github.com.  Instead if you remove the contributing file [from the excludes array](https://github.com/github/open-source-guide/blob/gh-pages/_config.yml#L7) you should be able to link to the published version.

For bonus points, you can even remove the `layout: default` and front matter, as that's included automatically.

**Comment by divayprakash** [comment]
@benbalter Working on it!

**Comment by divayprakash** [comment]
@benbalter As I understand it, the first step to solving this involves removing the contributing file from the excludes array in `_config.yml`. This should cause the file to be included in the Jekyll page build and then I should be able to link to it from the navbar. Is this what you're looking for?

>For bonus points, you can even remove the layout: default and front matter, as that's included automatically.

Where exactly does this need to be done? Sorry but I'm a beginner at Jekyll so I am just trying to get to grips with the entire project.

**Comment by divayprakash** [comment]
As an aside, the same issue is present if you click on the 'About' link on the navbar.

**Comment by nayafia** [comment]
I'm :thumbsup: if someone wants to submit a PR with this (for both "About" and "Contribute" links)
