### ISSUE TITLE
Is this repo maintained?

### ISSUE THREAD

**Issue by alroniks** [github/opensource.guide#2391]
I see a lot of issues here with very weird content, they look like spam or just without any sense. 

Is it still a live project?

**Comment by alroniks** [comment]
@gallexi Seems you merged the last pull requests. Please, have a look.

**Comment by alroniks** [comment]
Good to know. Thank you @mlinksva

**Comment by MikeMcQuaid** [comment]
> Is it still a live project?

Yes. Check the merged PRs rather than the issues.



> I see a lot of issues here with very weird content, they look like spam or just without any sense.

Yes, this repo attracts a lot of spam.
