### ISSUE TITLE
i18n capabilities

### ISSUE THREAD

**Issue by webknjaz** [github/opensource.guide#288]
Hi,

My friends and I would like to translate this resource into Ukrainian. I saw in `CONTRIBUTING.md` that you encourage contributing translations. But I don't see any localisation/internationalisation infrastructure in the repo.

Could you please share any plans on changing the folder structure (like having one folder per locale with the same set of files as English)? Or maybe you plan using any i18n `_` markers?

Looking forward to hearing your thoughts :)

Warm regards,
Sviatoslav.

**Comment by sigerello** [comment]
@webknjaz I'm ready to help in Ukrainian translation.

**Comment by m1guelpf** [comment]
I could also help with an spanish translation.

**Comment by McAlyster** [comment]
Hey, that would be a pleasure to help you guys for a translation in french.

**Comment by xoan** [comment]
Hi,

There is a branch named [```i18n```](https://github/open-source-guide/tree/i18n). There are no commits ahead ```gh-pages```, but seems to be there for this purpose, right?

PS. Jekyll has a plugin for internationalization that looks very easy to use and mantain: [Jekyll Multiple Languages plugin](https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin)

**Comment by numrut** [comment]
Hi @xoan. That branch was created just about 3 hours ago. It is likely it was the result of this issue.

I think, we have to wait a little for the mainteiners' clarifications.

**Comment by xoan** [comment]
@numrut wrote:
> I think, we have to wait a little for the maintainers' clarifications.

I agree :)

**Comment by bkeepers** [comment]
Hey everyone, thanks for being so eager to help translate! I started https://github.com/github/open-source-guide/pull/295 to work on making this easier and would love feedback.

@webknjaz if you're up for it, I'd love your help working through this on a Ukrainian translation.

**Comment by webknjaz** [comment]
Thanks @bkeepers, I'm in. I'll be glad to help!
So what's the plan? Create new branch with Ukrainian translation in a fork having a bunch of articles in a folder structure mimicking English one?

**Comment by webknjaz** [comment]
@sigerello and @numrut,
I've invited both of you to join [the team](https://github.com/orgs/open-craft-guild/teams/translators). I'll need your emails to send you slack invitations as well.

**Comment by bkeepers** [comment]
@webknjaz just to clarify what I tried to articulate in #295, but I think your fork should _only_ contain the Ukranian translation.

If anyone has free time this week and interest in doing another translation, I'd be up for kicking that off and opening an issue like #299 for your language. I don't want to do more than a couple while we're still ironing out how exactly it will work, but a couple might help to get more feedback.

**Comment by webknjaz** [comment]
@bkeepers any thoughts on localisation of pictures? should they go into the locale folder?

**Comment by bkeepers** [comment]
@webknjaz oooh, great question. For now, maybe create a locale folder in `assets/images/`?

**Comment by webknjaz** [comment]
sounds good

**Comment by webknjaz** [comment]
@bkeepers there's additional concern, which bothers me for a while: fixes or improvements to original articles go to this repo and there's no way to automatically confirm that translated version still corresponds original one.
I'm thinking of adding a commit hash of the repo state to translated article metadata stating that it's valid for that version. There could be an automated check with notification of translators listing articles which need to be updated (probably with diff) or re-confirmed that they are still relevant.

**Comment by webknjaz** [comment]
Still in progress

**Comment by Nader-Zubaid** [comment]
nader79zubaid.wordpress.com

**Comment by webknjaz** [comment]
spam?
