### ISSUE TITLE
Guide: How to fork projects

### ISSUE THREAD

**Issue by thejameskyle** [github/opensource.guide#289]
We talked at @maintainerati about how it would be great to document the best practices around forking projects including stuff like:

- How to make sure you really need to fork
- How to fork while keeping the original maintainer in mind
- How to setup your fork so the community can adopt it easily
- How to communicate with the community about your fork
- How to merge back in with the original project and when it makes sense to do that
- How to work with maintainers to deprecate the original project and when it makes sense to do that

There's probably a lot more you can cover here, but this would be a good starting point

**Comment by nayafia** [comment]
I'm :thumbsup: on this, if someone wants to tackle it!

We'll need to clarify that this is about "project forks" and not a lightweight "GitHub"-type fork (*don't I just click the fork button?* :trollface:).

We should also link to this guide from the "Leadership and Governance" guide.

**Comment by mlinksva** [comment]
Good prior art/reference: https://jamesdixon.wordpress.com/forking-protocol-why-when-and-how-to-fork-an-open-source-project/ (2009)

**Comment by jowagner** [comment]
@stale: One week notice for closing an issue due to inactivity is way too short. The issue owner may be on vacation or be busy with other work.

**Comment by mlinksva** [comment]
@jowagner feel free to open a PR suggesting a different timeframe. It's specified for this repo at https://github.com/github/opensource.guide/blob/9983df5a9aec88fb495bcb53f832dc3ba0d2c7a7/.github/stale.yml#L6

If you're interested in helping with stalebot generally, the code is at https://github.com/probot/stale ... I have my own [wishes](https://github.com/probot/stale/issues/73) for attenuation there. 😄 

Finally, `@stale` addresses a user with that name, not the bot. I suppose this is a bit confusing! 🤔

**Comment by jowagner** [comment]
Thanks. I'll look into it on the 27th.
