### ISSUE TITLE
Contribution about making OSS a business from the beginning

### ISSUE THREAD

**Issue by lukaseder** [github/opensource.guide#292]
Hi there, nice website.

I was browsing this part, which is always of particular interest to me:
https://opensource.guide/getting-paid

I think the whole website is a bit biased towards what is mentioned on that above link:

> Much of open source work is volunteered. For example, someone might come across a bug in a project they use and submit a quick fix, or they might enjoy tinkering with an open source project in their spare time.

This is a shame. I wish our industry would step up and start being more entrepreneurial. There are a lot of us out there who see OSS as a means to an end (improved market reach and time to market, market validation, commoditisation of one of many products, etc.) not a philosophy.

If that point of view is interesting to you, I'd be happy to contribute. Here are some articles on the subject that I've written in the past:

- https://opensource.com/business/14/1/how-to-transition-open-source-to-revenue
- https://opensource.com/business/14/1/5-lessons-open-source-revenue-based-model

**Comment by GeekyShiva** [comment]
@lukaseder are you suggesting that there should be more emphasis on moving towards revenue based model for Open source projects , but can you give a valid point why such approach should be taken? in contrast to a normal unbiased approach 

on the other hand the https://opensource.guide/getting-paid is largely unbiased and puts forward the look of present OSS as it is being fair and balanced .

**Comment by lukaseder** [comment]
Well :)

Your existing page is _very_ biased in fact. It's biased towards OSS being an undisputable goal per se (and then optionally asking for money), rather than writing software for a living (and then choosing a licensing / marketing / sales model, which may or may not include OSS).

My suggestion was in favour of removing or weakening your existing bias, or at least of discussing the option that some people / companies choose OSS only for marketing reasons because of the very compelling price and legal model for consumers, e.g. to get the foot in their doors.

Your page starts like this:

> Why some people seek financial support

Well, some people don't even ask themselves this question. Of course we all want to make money. The question for those people is: "why some people include OSS in their licensing strategy"

I thought this would be an interesting "alternative" point of view that is currently completely missing on your website. YMMV.

**Comment by lutzhorn** [comment]
I don't see why helping $COMPANY getting a foot in my door is a recommendable thing, especially if $COMPANY is using FLOSS only for marketing reasons.

**Comment by GeekyShiva** [comment]
@lukaseder i got your point .... somewhat , why don't just make the damn changes and then we can further look upon pushing it to the master ?? What say ? 

It looks somewhat correct the licensing part but i highly recommend please fork the repo and make changes .....i can contribute to it further once you are done here :)

**Comment by bkeepers** [comment]
Reminder that this is a place for respectful conversations. I've locked the conversation for now and will reopen it in a few days.

**Comment by MikeMcQuaid** [comment]
Passing on this suggestion, sorry.
