### ISSUE TITLE
[suggestion] New guide: creating your first pull request

### ISSUE THREAD

**Issue by kytrinyx** [github/opensource.guide#304]
@hzoo wrote in #284

> creating your first PR [...] should be a topic too

@sgrif did a great talk called "The Anatomy of a Pull Request". It doesn't look like the video ever got posted anywhere, but if it does it would make an excellent resource.

@cbeams wrote https://chris.beams.io/posts/git-commit/ which is my all-time-favorite article about how to write good git commits. It is also applicable to pull requests.

@keavy wrote https://github.com/blog/1943-how-to-write-the-perfect-pull-request 

After a few frustrating interactions with some newer contributors I wrote http://tinyletter.com/exercism/letters/exercism-pull-requests

**Comment by hzoo** [comment]
Awesome 😄! Would be cool to talk about:

- some of the tips we all have (almost like RFCs)
- as well as the workflow: initial PR (title, description, who to ping (if at all), maybe should make an issue before the PR, taking feedback and responding to comments, awareness that merging a pr may not be immediate or may not even be accepted unless an issue was created before and was approved, time to merge vs release, etc
- maybe link examples of PRs that we think are good and why?

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
hmm

**Comment by HansZwetslootAktionAktivAnarkist** [comment]
l still looking for coworkers to my project. aerolab interacts poorly

**Comment by kytrinyx** [comment]
One thing that came up at Maintainerati last week: project scope will determine whether or not a PR will be accepted (or should be accepted). One thing we might talk about is how to figure out before putting in a whole lot of work whether or not this change is something the project is open to / willing to consider.

**Comment by hzoo** [comment]
> figure out before putting in a whole lot of work whether or not this change is something the project is open to / willing to consider.

👍 . Kinda like what I was saying about not accepting a PR unless an issue was created before if it's a big change. We can also mention a more formal process such as doing RFCs (https://github.com/emberjs/rfcs).

**Comment by kytrinyx** [comment]
I believe this still is worth keeping open. The next step on this is to write a bullet-point list of points/ideas/topics that should go into it, and then structure those in a rough outline for review.

**Comment by kytrinyx** [comment]
Here's the link to @sgrif's video: https://www.youtube.com/watch?v=u2xzRUYrsWA
