### ISSUE TITLE
Improving ebook formats

### ISSUE THREAD

**Issue by bkeepers** [github/opensource.guide#316]
@sapegin got us rolling with ebook formats in #273. Like everything with these guides, the ebooks will never be "done", but we should make a concerted effort to make them a first-class citizen of this project. Here's a list of what else needs done:

- [x] Generate epub / mobi formats #305
- [ ] Generate and publish ebooks as part of build or release process
- [ ] Create a custom covers #318 
- [ ] Generate ebook from custom HTML/CSS to improve design and readability
- [ ] Link to ebook formats on website
- [ ] Publish the ebooks to Amazon/iTunes/Google Play/wherever else people get ebooks

What else should be added to this?

**Comment by m1guelpf** [comment]
Subscribing

**Comment by m1guelpf** [comment]
Subscribing

**Comment by sapegin** [comment]
@m1guelpf Just click “Subscribe” button, no need to tell everyone.

**Comment by m1guelpf** [comment]
@sapegin Sorry 😞

**Comment by m1guelpf** [comment]
Any updates on this?
