### ISSUE TITLE
Requesting and submitting new features

### ISSUE THREAD

**Issue by danielbachhuber** [github/opensource.guide#323]
It'd be helpful to have some language (maybe in "[How to Contribute](https://opensource.guide/how-to-contribute/)") around:

1. How to request a new feature (e.g. open an issue for discussion before investing time into it, potentially).
2. How to submit a new feature (e.g. pull request etiquette / don't include multiple new features in the same pull request).

**Comment by kytrinyx** [comment]
I think there are three ideas here, that we might treat individually (or not).

1. "here's how to avoid investing time into something that the project doesn't want"
1. "figure out how the project wants you to suggest features"
1. "here's how to open a great pull request"

In the [opening an issue](https://opensource.guide/how-to-contribute/#opening-an-issue) section of How to Contribute we say:

> You should usually open an issue in the following situations:
> [...]
> * Propose a new feature or other project idea

This is sometimes true, but projects often have documented policies around how to suggest new features.

I think we should probably tweak the How to Contribute guide to include the first two points, and link to a separate guide for the third.

**Comment by nayafia** [comment]
Hi! There's some info in "How to Contribute" that addresses these points, specifically:

* ["Communicating Effectively"](https://opensource.guide/how-to-contribute/#communicating-effectively)
* ["Opening an Issue/PR"](https://opensource.guide/how-to-contribute/#opening-an-issue)

What else were you thinking of adding?
