### ISSUE TITLE
Translation: Chinese 

### ISSUE THREAD

**Issue by lijiangsheng1** [github/opensource.guide#328]
Repository: https://github.com/OCselected/open-source-guide
Preview: https://ocselected.github.io/open-source-guide/
Locale: `zh-CN`

On the `gh-pages` branch of your fork:

- [x] Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/local/en-US.yml` to a new file with the name of your locale and translate the strings.
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [x] best-practices.md
  - [x] building-community.md
  - [x] code-of-conduct.md
  - [x] finding-users.md
  - [x] getting-paid.md
  - [x] how-to-contribute.md
  - [x] leadership-and-governance.md
  - [x] legal.md
  - [x] metrics.md
  - [x] starting-a-project.md
- [ ] ??? TODO - other steps here
- [x] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [x] Open a Pull Request on the [upstream repository](https://github.com/github/open-source-guide) to add your fork to `translations` in `_config.yml`

**Comment by lee-dohm** [comment]
As stated in #299, please don't start any new translations until we've had the opportunity to make sure our proposed process works. Since this isn't something we're ready to support, I'm going to close this Issue for now. You may want to subscribe to #299 for updates in the meantime.

**Comment by bkeepers** [comment]
@lee-dohm, I actually said in https://github.com/github/open-source-guide/issues/288#issuecomment-281137887: 

> If anyone has free time this week and interest in doing another translation, I'd be up for kicking that off and opening an issue like #299 for your language. I don't want to do more than a couple while we're still ironing out how exactly it will work, but a couple might help to get more feedback.

My mistake for not communicating that more clearly.

**Comment by bkeepers** [comment]
@lijiangsheng1 Thanks for kicking this off!  Would you mind pushing your translations to the `gh-pages` branch so GitHub Pages builds the website for them?

**Comment by lee-dohm** [comment]
Ah ok, I missed that. Thanks @bkeepers and my apologies :bow:

**Comment by lijiangsheng1** [comment]
@bkeepers thanks for your encourage.  @lee-dohm It's ok .

OK, I will push branch which name is `gh-pages-translation-chinese`.

**Comment by bkeepers** [comment]
> OK, I will push branch which name is `gh-pages-translation-chinese`.

@lijiangsheng1, let's get your fork rendering on https://ocselected.github.io/open-source-guide/. To do that, you'll need to merge the `gh-pages-translation-chinese` branch in to `gh-pages` and push to your fork. Once you've pushed to the `gh-pages` branch, the guide should show up on https://ocselected.github.io/open-source-guide/. This way people can see the progress as your translation progresses.

**Comment by lijiangsheng1** [comment]
@bkeepers Thanks for your help. I just merged `gh-pages-translation-chinese` to gh-pages`, But [https://ocselected.github.io/open-source-guide/](https://ocselected.github.io/open-source-guide/) not work, Could you help me  review that ?

**Comment by bkeepers** [comment]
Hey @lijiangsheng1, sorry for the issue. It's been fixed in #348. If you merge the latest changes from the `i18n` branch in #295 into your `gh-pages` branch, it should work now.

**Comment by lijiangsheng1** [comment]
@bkeepers It's work now,Thanks very much! I will update it.

**Comment by liadbiz** [comment]
@lijiangsheng1 I am almost done with translation. Chekout my repo https://github.com/liadbiz/opensource-contribute-guide-chinise
feel free to use it~:blush:

**Comment by lijiangsheng1** [comment]
O, Very great job. I'll review and merge to main branch gh-pages.  Thanks a lot. @liadbiz you can access  [https://ocselected.github.io/open-source-guide/how-to-contribute/](https://ocselected.github.io/open-source-guide/how-to-contribute/) . I'll update every weekly.

**Comment by liadbiz** [comment]
@lijiangsheng1 I have post it to my blog, which is generated by hexo. I will finished  the last two articles this weekend. just mention me if I can help :)

**Comment by joqk12345** [comment]
@lijiangsheng1 i made a picture of a brain map  for chapter one ,if u need i post it out in chinese.

**Comment by lijiangsheng1** [comment]
@joqk12345 You are great! Would you mind commit PR  to my fork, I need more time for merge main branch. I will sync translation later.

**Comment by Jasonnor** [comment]
@lijiangsheng1 I have just sent a PR, but may be related to the changing of main repo, please come to see 😄

**Comment by zoejane** [comment]
@liadbiz 
Really thank you for providing us the translation of all articles of Open Guide!

@lijiangsheng1 
Really thank you for maintain the project of open-source-guide(Chinese Translation)!

I see your discussion here, so I try to add the translation of @liadbiz to the repo of @lijiangsheng1 , and send a Pull Request,
Here is the PR link -  [add translation of all remaining articles by @liadbiz OCselected/open-source-guide#7](https://github.com/OCselected/open-source-guide/issues/7)

Before the PR be merged, 
You can also preview this Open Source Guide(Chinese Version) here first - http://blog.zoejane.net/open-source-guide/

**Comment by liadbiz** [comment]
@zoejane  Thanks! Really good work, I translated articles several months ago, and I remember there exists some mistakes that needto be fixed. It would be great you can proofread all the content :+1:

**Comment by zoejane** [comment]
@liadbiz 
When I first saw the Open Source Guide, I really wish there would be a Chinese Version. But I am not so good at translation, and don't have enough time and energy to do such a work.
So when I Googled and found your translation accidently , I am so happy! And it is so glad that I have the opportunity to say thanks to you!
I‘ve fixed some typos when I add you translation to the PR, but I haven't read the whole articles deeply, yet. I will read it more and try my best to proofread it, because this is such a great guide :)

**Comment by lijiangsheng1** [comment]
@zoejane @liadbiz 
Great jobs! Thanks very much.

**Comment by lijiangsheng1** [comment]
@zoejane @liadbiz @Jasonnor 

I Just merged Zoe 's PR, but I find a lots of translate issue. (Sorry, @liadbiz Please don't mind) . 

Now, We are just finished step 1 , still need a lot of review jobs. Because not good, If you read it in Chinese, You can't understand clear. 

Thanks all, Enjoy it.

**Comment by liadbiz** [comment]
@lijiangsheng1 I am sorry for translate and typo issues, and thanks for point it out! I have some time this weekend, we can make it better. Last but not least, half of that were translated by @cnbo.
@zoejane You are so kind, just enjoy the contribution. :smile:

**Comment by zoejane** [comment]
@lijiangsheng1 I just saw you update the whole translation of building-community 3 hours ago, and thank you for your patience and professional attitude.
Together we can try and make it better.
I will try my best :)

**Comment by lijiangsheng1** [comment]
..... I will sync and PR .

**Comment by lijiangsheng1** [comment]
my fork repo name is open-source-guide, I used script/sync-translation can't work. So  I need more time to fix this or fork anther repo.
