### ISSUE TITLE
Translation: Brazilian Portuguese

### ISSUE THREAD

**Issue by nandomoreirame** [github/opensource.guide#342]
Repository: https://github.com/nandomoreirame/open-source-guide
Preview: https://nandomoreirame.github.io/open-source-guide
Locale: `pt-BR`

On the `gh-pages` branch of your fork:

- [x] Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/local/en-US.yml` to a new file with the name of your locale and translate the strings.
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [x] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [ ] starting-a-project.md
- [ ] ??? TODO - other steps here
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/open-source-guide) to add your fork to `translations` in `_config.yml`

**Comment by bkeepers** [comment]
Hey @nandomoreirame, thanks for kicking this off! Just so you're aware, the translation process is still very much a work in progress. So you're signing up for both glory and suffering. 

First, let's get your fork rendering with the changes in #295. To do that, you'll need to merge the `i18n` branch in to your `gh-pages` branch and push to your fork. Ideally, GitHub Pages would let us do this from a different branch, but this will have to do for now.

Once you've pushed to the `gh-pages` branch, the guide should show up on https://nandomoreira.me/open-source-guide/.

**Comment by CesarNog** [comment]
Hey all, I am willing to help with Brazilian Portuguese language as well. How can I help?

**Comment by luciano-jr** [comment]
I am available to help with pt-BR translation as well.

**Comment by vcapretz** [comment]
@nandomoreirame I would like to help you with the translation! what's the current status? can I fork your repo and start working with you?

**Comment by bkeepers** [comment]
Hey @nandomoreirame, there was an issue preventing the site from building on forks that has been fixed. If you merge the latest from the `i18n` branch into your `gh-pages` branch, it should render on https://github.com/nandomoreirame/open-source-guide/ now

**Comment by nandomoreirame** [comment]
Thanks @bkeepers I do it 👍  look > https://nandomoreira.me/open-source-guide/

@CesarNog @luciano-jr @vcapretz Can you help yes, just give a fork in the repo
https://github.com/nandomoreirame/open-source-guide/

Thanks guys 🤘

**Comment by vcapretz** [comment]
@nandomoreirame I started translating and there's a page about maintainers, but I don't think "mantedor" is a good translation for that world, have any suggestions?

**Comment by lnfnunes** [comment]
@vcapretz AFAIK the correct is "mantenedor"...

**Comment by vcapretz** [comment]
@lnfnunes thank you!

**Comment by vcapretz** [comment]
@nandomoreirame translated the first file > https://github.com/nandomoreirame/open-source-guide/pull/1

**Comment by tone2526** [comment]
Cc

**Comment by CesarNog** [comment]
Oh no, the probot-stale bot closed this issue?

**Comment by alexandrebarbaruiva** [comment]
is this still the branch used for translation? I'd like to contribute but it seems like there's no more activity here... (help?)

**Comment by nandomoreirame** [comment]
Yes, we need your help @alexandrebarbaruiva !! :)
Please submit your contributing to repo: https://github.com/nandomoreirame/open-source-guide
Thanks

**Comment by vcapretz** [comment]
@nandomoreirame could you open this issue again?

**Comment by nandomoreirame** [comment]
I also can not open the issue. @CesarNog please :)

**Comment by Twizzlerseffect** [comment]
Hi, I was wondering if it was still possible to work on this?

**Comment by guipaes** [comment]
@nandomoreirame still need help translating?

**Comment by nandomoreirame** [comment]
Hi guys, all send merge requests to the repository: https://github.com/nandomoreirame/open-source-guide

Thanks all ^^

**Comment by MikeMcQuaid** [comment]
@nandomoreirame Apologies this PR has been neglected for so long. I've merged the first translation to this repository (Spanish) and updated the documentation on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please submit a pull request when you have translated all articles and checked `./script/test` passes and I'll get it merged in ASAP. Thanks!
