### ISSUE TITLE
Standing on the shoulders of giants

### ISSUE THREAD

**Issue by theo-armour** [github/opensource.guide#371]
Any writing regarding open source software implies '[Standing on the shoulders of giants]( https://en.wikipedia.org/wiki/Standing_on_the_shoulders_of_giants )'.

Would it be a nice thing if the following condition was in the CONTRIBUTING document?

* Each guide includes a short bibliography or reading list of links at the end of the guide.
* The purpose is either to help the reader identify the sources of inspiration for the current guide or to present links for further reading on the topic.

Suitable links - along with a short description - submitted via GitHub Issues might be a fun way of involving the user community. Suggested links might need to have a certain number of thumbs-up votes in the issue in order to be included.

Here are a few sample suggestions for several of the guides:

#### Starting an Open Source Project

* [Free and open-source software]( https://en.wikipedia.org/wiki/Free_and_open-source_software ) ~ Free open source software as described by the elephant in the room

#### How to Contribute to Open Source

* [Readme Driven Development]( http://tom.preston-werner.com/2010/08/23/readme-driven-development.html ) ~ 'There must be some middle ground between reams of technical specifications and no specifications at all. And in fact there is. That middle ground is the humble Readme.'

#### Getting Paid for Open Source Work

* [How I Stumbled Upon The Internet’s Biggest Blind Spot]( https://medium.com/@nayafia/how-i-stumbled-upon-the-internet-s-biggest-blind-spot-b9aa23618c58 ) ~  insightful investigation on the status of funding for open source projects

**Comment by bkeepers** [comment]
Early versions of the site actually included a list of links at the end of each article. Some of the lists were really long and started to feel like a grab-bag of anything that's ever been written about a topic. So we ended up deciding to inline all of the links into the text, and if there wasn't anything in the resource that was worth alluding to in an inline reference, then we should just remove it.

I still think that was the right decision for now, but would be happy to hear counter arguments. I'm going to close this issue for now, but feel free to keep discussing and we'll reopen if the consensus is to add links back to the bottom.

cc @nayafia

**Comment by nayafia** [comment]
Yep - as @bkeepers said, we used to have a "Further Reading" section for each, but decided to move to inlink links + pull quotes. Thanks for the suggestion though, and the opportunity for us to clarify where the current format comes from.

**Comment by theo-armour** [comment]
@bkeepers 

>Some of the lists were really long and started to feel like a grab-bag of anything that's ever been written about a topic

I hear you. This is one reason I nominated giants and not midgets, trolls and dumbfucks. 

A bibliography succeeds by useful curation. Links **must** be moderated.

> if there wasn't anything in the resource that was worth alluding to in an inline reference, then we should just remove it.

Interesting filter

Does this not imply a self-referential universe? That is to say that links that agree/fit-in with the text are the only allowable links?

@nayafia 

> Thanks for the suggestion though, and the opportunity for us to clarify where the current format comes from.

Agreed. As the GitLab peeps say: [write everything down]( https://blog.ycombinator.com/gitlab-distributed-startup/ )!!!

***

The current inline links are kind of fun. They remind me of an [advent calendar]( https://en.wikipedia.org/wiki/Advent_calendar): You have no idea what happens when you open the door/link/pull the trigger.

On the other hand the inline links may be less helpful when at a later date you want to return to one of the guides and try to locate the link you kind of remember was useful but do not exactly remember which term in the text links to the source you are looking for.

Also the inline links make for an interesting reading process. Do you click on the links as you read them? Or should you read the text and then click on the links? Or should you just ignore the links for now?
