### ISSUE TITLE
Mismatch between footer buttons on hover

### ISSUE THREAD

**Issue by mkermani144** [github/opensource.guide#378]
Footer buttons have different hover effects, one of which having smooth color change with 0.2s transition duration and the other having no transition duration at all.

![issue](https://cloud.githubusercontent.com/assets/12621708/24692184/f8d158a2-19ec-11e7-93e3-8c3628efeec0.gif)

**Comment by nayafia** [comment]
Thanks for the note, @mkermani144!

Tagging @sophshep to see about a fix. PRs are also welcomed. :)

**Comment by nayafia** [comment]
Quick look suggests the one on the right is a MailChimp embed (with an input tag), whereas the left is a link that uses our custom styles, hence the difference.

**Comment by sophshep** [comment]
The reason these were different is that the one on the left is a `<a>` link, which has a transition applied to it. The form is an `<input>` which doesn't - but putting a transition on the class for the button solves it!

**Comment by mkermani144** [comment]
@nayafia @sophshep Yes, I know why one of the buttons has a transition and the other doesn't, but I think as users _think of_ both as buttons, it's better to make the transitions the same.
