### ISSUE TITLE
Want to speaking at Open Source summit China

### ISSUE THREAD

**Issue by lijiangsheng1** [github/opensource.guide#382]
![image](https://cloud.githubusercontent.com/assets/1545933/24826561/8ef1b1da-1c6b-11e7-8cef-a2b42b5926d2.png)

Dear open source guide contributors,

  4.19~4.20 have a open source summit in Beijing China, as a  speaker , I want to talk about this project, and try to let more people know this great project. My topic title is 《deep into open source guide》.

 But I need more good advices, suggestions.  let me know your thoughts in the comments.

**Comment by kytrinyx** [comment]
@lijiangsheng1 Congratulations on getting your talk accepted to the Open Source Summit China. ✨ 

> But I need more good advices, suggestions.

What type of advice are you looking for?

What is the main goal for your talk?
What is your main point, and how are you thinking of building up to it?

**Comment by lijiangsheng1** [comment]
@kytrinyx  Thanks very much. Thanks for your question. I think I know what I will say. 
BTW: sorry for reply later.

**Comment by kytrinyx** [comment]
@lijiangsheng1 Best of luck with your talk!
