### ISSUE TITLE
Translation: Spanish

### ISSUE THREAD

**Issue by consugus** [github/opensource.guide#383]
Repository: https://github.com/consugus/opensource.guide
Preview: https://consugus.github.io/open-source-guide/
Locale: `es-AR`

- [x] Merge the `i18n` branch into `gh-pages` and push the branch to your fork. This should build the website and it should be visible at the preview url above.
- [x]  Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [x] best-practices.md
  - [x] building-community.md
  - [x] code-of-conduct.md
  - [x] finding-users.md
  - [x] getting-paid.md
  - [x] how-to-contribute.md
  - [x] leadership-and-governance.md
  - [x] legal.md
  - [x] metrics.md
  - [x] starting-a-project.md
- [x] ??? TODO - other steps here
- [x] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [x] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by consugus** [comment]
want to colaborate with the open translation? contact us

**Comment by m1guelpf** [comment]
@consugus I would like to help!

**Comment by consugus** [comment]
@m1guelpf nosotros somos un grupo de estudiantes de Ingeniería en Sistemas en Córdoba, Argentina y estamos oganizándonos para esta traducción con un grupo de compañeros. Va a ser un placer sumarte al grupo. Solo te pido que me tengas un poquito de paciencia hasta que podamos organizarnos bien, y en breve vuelvo a contactarte para coordinar una parte de la tarea contigo. Saludos,

**Comment by m1guelpf** [comment]
@consugus De acuerdo. Vais a traducirlo a español España o a español Hispanoamérica?

**Comment by consugus** [comment]
@o no creo que estemos en condiciones de poder hacer una traducción a español de España que sea suficientemente fiel. Tal vez podamos intentar hacer algo más neutral, si te parece bien. Para ello luego de tener algún documentos ya traducido te podré solicitar que lo revises para que opines si el trabajo hecho nos quedó muy latino.
De momento te voy enviando la invitación al fork que ya hice del repositorio, yo comencé con una prueba muy simple para evaluar la complejidad que podía revestir la edición sobre el artículo "How to contribute.md" y aparenta ser bastante sencillo el trabajo que hay que hacer porque hay bastante texto

**Comment by m1guelpf** [comment]
@consugus Te he mandado un PR como prueba

**Comment by consugus** [comment]
@m1guelpf Todo perfecto, ya hice el merge. No hay ninguna diferencia a lo que yo hubiera traducido del contenido que tradujiste. No creo que haya ningún inconveniente respecto de si la traducción es al español de España o latino si hacemos el esfuerzo por no utilizar vocabulario muy local

**Comment by consugus** [comment]
@m1guelpf quería hacer notar una dificultad que puede darse en páginas HTML con el uso de caracteres especiales como las vocales acentuadas, la eñe, etc: dependiendo del tipo de codificación que tenga seteado el navegador del cliente, en algunas ocasiones puede llevar a una mala visualización de la página usar solamente á (), es mas conveniente representarla como &aacute; que al momento de renderizar se verá sin problemas como una á.
Te dejo el link a una página con las formas de codificar estos caracteres y que no se genere ningún problema, cualquiera sea el tipo de codificación del navegador del cliente:
http://librosweb.es/libro/xhtml/capitulo_3/codificacion_de_caracteres.html

**Comment by consugus** [comment]
@m1guelpf con unos compañeros ya casi terminamos de traducir todo el sitio, hay un par de documentos que se completarán en un par de días y estaba quedando el documento "How to contribute.md" sobre el que habías hechos algunas contribuciones. Nuestra idea es tener todo completado para el próximo fin de semana y en ese momento poder hacer una peer-review entre nosotros para recién solicitar un PR a la gente de la página. Yo había preferido no tocar el documento "How to contribute.md" para que no hubiera conflictos con lo que estabas haciendo. Ahora voy a retomarlo y calculo que lo terminaré hasta hoy en la noche. Agradecemos tu colaboración. Saludos,

**Comment by m1guelpf** [comment]
@consugus De acuerdo, avisame a ver si puedo ayudar con la revisión.

**Comment by consugus** [comment]
Hola @m1guelpf , muchas gracias por tu generosidad. Los documentos que yo traduje y que ya estarían listos para ser revisados son:
* building-community
* finding-users
* how-to-contribute
Si pudieras ir revisando esos (o alguno) sería una gran ayuda. Nosotros por este lado vamos a tratar de comenzar con la revisión a partir de este fin de semana. Te pido que me avises qué documento estás revisando y cuál piensas revisar luego de que termines (si tus tiempos te lo permiten), de manera que no se asigne el mismo documento para ser revisado por dos personas

**Comment by consugus** [comment]
Hola @m1guelpf , el fin de semana estuvimos viendo cómo dividir las revisiones para optimizar esfuerzos y tiempos. Yo hablé con los otros colaboradores del grupo para que, si estás de acuerdo, te encargues de revisar la traducción que hice sobre: 
* how-to-contribute
La intención que tenemos es ya poder estar en condiciones de hacer un PR para el 13-14/05, si pudieras ayudarnos sería fantástico.
Agradezco, como siempre, tu voluntad y dedicación. Saludos,

**Comment by m1guelpf** [comment]
@consugus Me pongo ahora mismo con ello, os avisaré en cuanto acabe :smile:

**Comment by m1guelpf** [comment]
@consugus Acabo de terminar mi review del how-to-contribute.md

**Comment by SidVal** [comment]
Me sumo, si necesitan ayuda en traducción me avisan.

Ví el PR #388 pero tiene conflictos, fijate porfa @consugus si podes depurar esos dos archivos así queda habilitado para el merge. :pray:

**Comment by consugus** [comment]
Hola @SidVal , gracias por ofrecerte.
Los documentos están todos traducidos, el tema es que desconocemos qué problema tienen los documentos que están listando en conflicto (ahora son cuatro documentos). Acabo de estar mirándolos lado a lado, en mi compu, en un lado el documento original en inglés (https://opensource.guide/) y en otro el preview que se puede hacer desde GitHub (https://consugus.github.io/open-source-guide/) y los encuentro iguales. No puedo encontrar qué es lo que está dando conflicto y no tengo acceso a ver qué reporte les está dando Travis CI.
Si puedes ayudarnos a encontrar qué es lo que está fallando y ayudarnos o tal vez apuntándonos qué es lo que no funciona será una gran ayuda. Saludos,

**Comment by SidVal** [comment]
Yo probaría borrarle de tu PR los archivos que te dice que tienen conflictos :P

**Comment by sebassdc** [comment]
Saludos! ¿Como les puedo ayudar?

**Comment by effieMoran** [comment]
Hola, Soy argentina y me interesa colaborar
