### ISSUE TITLE
Translation: Japanese

### ISSUE THREAD

**Issue by watilde** [github/opensource.guide#385]
Repository: https://github.com/ja-opensource-guide/ja-opensource-guide.github.io
Preview: https://ja-opensource-guide.github.io/
Locale: ja-JP

- [x] Merge the `i18n` branch into `gh-pages` and push the branch to your fork. This should build the website and it should be visible at the preview url above.
- [x] Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [ ] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [ ] starting-a-project.md
- [ ] ??? TODO - other steps here
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:
- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by watilde** [comment]
I'm planning to manage the status of the translation progress on https://github.com/ja-opensource-guide/ja-opensource-guide.github.io/issues/1.

**Comment by sotayamashita** [comment]
@watilde I am not sure the status of it. Do you need help?
