### ISSUE TITLE
Why is it important to use the description field?

### ISSUE THREAD

**Issue by DonRichards** [github/opensource.guide#389]
Accessibility and discoverability I'm assuming. But I frequently have to convince people why this is important. Limited bandwidth, screen readers or just simply fatigue of exploring repos.

**Comment by nayafia** [comment]
Hi @DonRichards, yes, it's useful for accessibility and discovery. I think of it as a one-liner "headline" for your repo.

I also think it helps the author think about how they'd explain their repo, and why it's valuable, to a stranger. Helps simplify your own thinking, which is a good exercise in itself!
