### ISSUE TITLE
A guide for writing the documentation

### ISSUE THREAD

**Issue by franciscop** [github/opensource.guide#393]
I would love contributing by writing a guide about how to write documentation (how meta). This issue is to discuss whether it is welcome and the scope of it.

**So first things first, is a documentation guide welcome?** I am guessing a strong yes [from your last survey](http://opensourcesurvey.org/2017/). I am not able to make the graphics though, so I would need help there.

## Scope

This is a rough outline of possible topics in no particular order:

- Documentation: sure thing. How to write it, including code examples, different styles/languages, examples of great docs, etc.
- JavaDoc/PHPDoc/JSDocs/etc: automatic documentation generator.
- Workflow and build process: making sure everything is up to date.
- Getting started: making it easy for your users to quickly use your project.
- Landing page: set the tone for the project and hook your users ([example](https://picnicss.com/)). Quick reference available.

Extra: I've seen too many times that the developers want to show the super-amazing-complex-feature of their project and scare the user when they should be able to showcase it in few lines.

## Process

I would start with an outline of the topics to discuss as agreed here, then work towards the first draft as I search for more information and quotes.

***

PS: in the same line that you write "If your project is hosted on GitHub, you can use GitHub Pages to easily make a website", would it be okay at all to link at some point to https://documentation.agency/ ? I just launched it for working with developers to improve their documentation.

**Comment by mlinksva** [comment]
Seems like a good idea to work out to me!

Regarding links, see https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md#ground-rules--expectations

> When adding content, please consider if is widely valuable. Please don't add references or links to things you or your employer have created as others will do so if they appreciate it.

But I'm really happy to see survey results being used as real motivation already. Congratulations on launching your agency. 🎉

**Comment by kytrinyx** [comment]
One resource that I have found invaluable is Mozilla's "Working Open Workshop". The entire contents of the workshop is included in writing there.

http://mozillascience.github.io/working-open-workshop

**Comment by diamonddocumentation** [comment]
Great idea! I am happy to work with you on this. I can contribute some useful documentation planning guidance e.g. thinking about the audience, tasks, requirements etc.

**Comment by franciscop** [comment]
Awesome, I'll get started then over the weekend. @diamonddocumentation awesome, how do you propose to do so?

**Comment by HarshitKaushik** [comment]
Hi @franciscop, great idea. Can I help by providing a list of common guidelines for writing good Javadoc in code, so that when we generate documentation with JavaDoc, it looks good?

I can provide a gist of (How to Write Doc Comments for the Javadoc Tool)[http://www.oracle.com/technetwork/java/javase/documentation/index-137868.html] for first time Java developers.
