### ISSUE TITLE
Link to CODE_OF_CONDUCT

### ISSUE THREAD

**Issue by gs-rezaem** [github/opensource.guide#399]
Why does the guide say "Place a CODE_OF_CONDUCT file in your project’s root directory, and link to it from your README, so it’s visible to your community." ?
The README seems like the wrong place for this. To wit, the [README](https://github.com/github/opensource.guide/blob/gh-pages/README.md) here doesn't do that.
Isn't CONTRIBUTING the right place to link CODE_OF_CONDUCT, or at least a good/better alternative?

**Comment by kytrinyx** [comment]
That's a fair point, @gs-rezaem. I think that it will depend on the project whether the README or the CONTRIBUTING file are the best place for this. @nayafia what do you think? Would it make sense to tweak the wording on this to emphasize the idea of _making it visible to the community_ and having a link in the README or CONTRIBUTING guide as a way to accomplish that?

**Comment by nayafia** [comment]
Yes! I think the main idea is to make sure that it's visible to your community, whether that's on the README, CONTRIBUTING, or wherever else.

@gs-rezaem feel free to open a PR with this change :thumbsup:

**Comment by gs-rezaem** [comment]
PR #411
