### ISSUE TITLE
Translation: Persian

### ISSUE THREAD

**Issue by MahdiMajidzadeh** [github/opensource.guide#405]
Repository: https://github.com/MahdiMajidzadeh/opensource.guide

Preview: https://mahdimajidzadeh.github.io/opensource.guide/
Locale: `fa-IR`

On the `gh-pages` branch of your fork:

- [x] Merge the `i18n` branch into `gh-pages` and push the branch to your fork. This should build the website and it should be visible at the preview url above.
- [x] Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [ ] Create a new directory in `_articles/` for your locale and translate each guide:
  - [ ] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [ ] starting-a-project.md
- [ ] ??? TODO - other steps here
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by MahdiMajidzadeh** [comment]
is any stylesheet for RTL languages?

**Comment by bkeepers** [comment]
> is any stylesheet for RTL languages?

@MahdiMajidzadeh there's not yet, but we'd love to work on adding support for it.

@sophshep @broccolini Have you done any work with RTL support in Primer? Any advice?

**Comment by sophshep** [comment]
> @sophshep @broccolini Have you done any work with RTL support in Primer? Any advice? 

We haven't. We could add a module that updates other things to format them for RTL - they way Primer is set up puts us in a good spot for this. It's low priority at the moment, but I've [created an issue](https://github.com/github/design-systems/issues/388) for it.

**Comment by sophshep** [comment]
In the meantime, we could create a custom stylesheet just for these guides. Since the design is on the simpler side, I don't think it would be too much effort.

**Comment by broccolini** [comment]
I was expecting us to need to add this at some point, definitely happy to help make that happen. Related I saw a good talk on writing modes a few months ago, it has a bit of history and interesting info that might be relevant: https://speakerdeck.com/jensimmons/writing-modes-at-css-day

**Comment by MahdiMajidzadeh** [comment]
I started make `rtl.scss` and I hope can finished and convert all style

https://github.com/MahdiMajidzadeh/opensource.guide/blob/gh-pages/assets/css/rtl.scss
