### ISSUE TITLE
Translations: Indonesian

### ISSUE THREAD

**Issue by willysr** [github/opensource.guide#408]
Repository: https://github.com/willysr/id-opensource.guide
Preview: https://willysr.github.io/id-opensource.guide
Locale: `id-ID`

On the `gh-pages` branch of your fork:
- [x] Merge the i18n branch into gh-pages and push the branch to your fork. This should build the website and it should be visible at the preview url above
- [x] Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/local/en-US.yml` to a new file with the name of your locale and translate the strings.
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [x] best-practices.md
  - [x] building-community.md
  - [x] code-of-conduct.md
  - [x] finding-users.md
  - [x] getting-paid.md
  - [x] how-to-contribute.md
  - [x] leadership-and-governance.md
  - [x] legal.md
  - [x] metrics.md
  - [x] starting-a-project.md
- [x] ??? TODO - other steps here
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [x] Open a Pull Request on the [upstream repository](https://github.com/github/open-source-guide) to add your fork to `translations` in `_config.yml`

**Comment by willysr** [comment]
@nayafia : i'm done with the translations
What should i do next before i send a pull request? Can you verify that everything is working?

I haven't change the CNAME to id.opensource.guide since it will break the preview (the images will not be shown so i made an absolute path for that)

Thanks

**Comment by nayafia** [comment]
Thank you @willysr, this is fantastic! :heart:

@bkeepers has been handling translations, so I'll leave it to him to follow up and review.

**Comment by willysr** [comment]
Added PR: https://github.com/github/opensource.guide/pull/429
