### ISSUE TITLE
Translation: German

### ISSUE THREAD

**Issue by jens1o** [github/opensource.guide#413]
Repository: https://github.com/jens1o/de-opensource.guide
Preview: https://jens1o.github.io/de-opensource.guide/
Locale: `de-DE`

On the `gh-pages` branch of your fork:

- [X] Merge the `i18n` branch into `gh-pages` and push the branch to your fork. This should build the website and it should be visible at the preview url above.
- [x] Update `title`, `description`, and `locale` in `_config.yml`
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [ ] Create a new directory in `_articles/` for your locale and translate each guide:
  - [x] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [x] starting-a-project.md
- [ ] ??? TODO - other steps here
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by jens1o** [comment]
I have a tiny problem:
When I push changes, I can see them on GitHub, but they won't be shown on the website...

**Comment by nayafia** [comment]
Hi @jens1o, thanks for getting started on a German translation! I'll defer to @bkeepers to tackle your qs.

**Comment by jens1o** [comment]
Thanks. :) I fixed the problem by remove the `_articles/en-US` folder with its content, now it works. :)

**Comment by jens1o** [comment]
nope ;)
I just lack of time unfortunately :/

**Comment by jens1o** [comment]
https://github.com/jens1o/de-opensource.guide/commit/afda47d62661acf81032a173258b81118cff7306

`Best-Practices` is finished!

**Comment by jens1o** [comment]
Starting a project is finished, too

**Comment by MikeMcQuaid** [comment]
@jens1o Apologies this issue has been neglected for so long. I've merged the first translation to this repository (Spanish) and updated the documentation on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please submit a pull request when you have translated all articles and checked `./script/test` passes and I'll get it merged in ASAP. Thanks!

**Comment by jens1o** [comment]
@MikeMcQuaid Alright, thanks.

**Comment by katrinleinweber** [comment]
Hi @jens1o! I wanted to [start translating](https://github.com/github/opensource.guide/pull/577) according to the [new site structure](https://github.com/github/opensource.guide/blob/master/docs/translations.md) as well. Do you still have the repo so I can contribute there? Or shall I invite you to [mine](https://github.com/katrinleinweber/opensource.guide/commits/de)? Or @MikeMcQuaid can we both get write access to a `de` branch here?

**Comment by jens1o** [comment]
@katrinleinweber Could you invite me to yours please? I've deleted mine, since it was out-of-date.

**Comment by katrinleinweber** [comment]
People don't want backup, people want restore ;-)

No worries! I [pushed a draft translation of `best-practices`](https://github.com/katrinleinweber/opensource.guide/commit/920ecc1efcacf2a4fdde16c720426cc567dcebe2). Please feel free to rewrite it and force-push to remove the `WIP` in the commit message. But only there, please ;-)

I will also stop force-pushing now.

Once I am finished with `metrics`, how about we start indicating which article we are working on by starting a branch named `de-filename` and a PR against `de` in my repo, so #577 grows whenever a new file is complete?

**Comment by jens1o** [comment]
Sounds good :)

**Comment by xDeaRxDeViLx** [comment]
> People don't want backup, people want restore ;-)
> 
> No worries! I [pushed a draft translation of `best-practices`](https://github.com/katrinleinweber/opensource.guide/commit/920ecc1efcacf2a4fdde16c720426cc567dcebe2). Please feel free to rewrite it and force-push to remove the `WIP` in the commit message. But only there, please ;-) I too will stop force-pushing now.
> 
> Once I am finished with `metrics`, how about we start indicating which article we are working on by starting a branch named `de-filename` and a PR against `de` in my repo, so #577 grows whenever a new file is complete?
