### ISSUE TITLE
translation in hindi

### ISSUE THREAD

**Issue by grbknr1996** [github/opensource.guide#419]
Hindi is a popular language and about 1.2 billion people speak hindi it would be better if we  make a hindi version

**Comment by nayafia** [comment]
Hi @grbknr1996, thanks for your interest! @bkeepers can answer more questions about the translations process, but I'd suggest checking out these issues:

https://github.com/github/opensource.guide/issues/383 (use this checklist)
https://github.com/github/opensource.guide/pull/359

...or [searching issues for "translation"](https://github.com/github/opensource.guide/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20translation) to see how others are handling it.

**Comment by grbknr1996** [comment]
thanks

**Comment by princeomkaar** [comment]
I 'am new here! I can translate English to Hindi!

**Comment by subkrish** [comment]
@bkeepers I am interested in contributing to this issue by working on the translation. Is there a place where I can start? Would I need to open an issue like it has been done for the other translations in other issues? How do go about it?

**Comment by bkeepers** [comment]
Hey @grbknr1996, @princeomkaar, & @subkrish! Thanks for your interest in translating the guides in to Hindi!

Check out https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md#starting-a-translation for more information on starting a translation. Let me know if you have any questions or need help with anything.
