### ISSUE TITLE
Open source guide for creating a repo in Linux 

### ISSUE THREAD

**Issue by StevenCopeland** [github/opensource.guide#433]
Do you think you could make a guide for creating a repo(or setting up with code you already have), I mean, even if it is impossible to create a repo from the terminal, maybe how would you create one online, clone it down, transfer the code over, stage and commit, and push **OR** you could make a Github desktop version for Linux. I would like a guide on this because, even though I figured it out, it took me a couple hours  in which I could have been programming in.

**Comment by mlinksva** [comment]
I can't put my finger on it, but this kind of step-by-step technical how-to documentation seems out of place for this project.

Documentation on [new guides](https://github.com/github/opensource.guide/blob/20ba2b71f738947efcda6090c7c958882a82ac50/docs/new-guides.md).

FWIW you might want to follow https://github.com/desktop/desktop/issues/1525 about Desktop on Linux or look at building and running it yourself https://github.com/desktop/desktop/pull/2271 or you can use https://hub.github.com to create a repo from the command line.

**Comment by nayafia** [comment]
Hi @StevenCopeland, thanks for the suggestion!

I agree with @mlinksva that this is probably too technical and GitHub-specific for an open source guide. However, I think this could be a great candidate for content that GitHub would offer elsewhere. I've passed it on to the appropriate team, thank you for letting us know!

**Comment by nayafia** [comment]
@StevenCopeland A colleague also pointed me to this: https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/

Hope it helps for the future :)

**Comment by StevenCopeland** [comment]
Thanks! That really helps!
