### ISSUE TITLE
Translation: Hindi

### ISSUE THREAD

**Issue by subkrish** [github/opensource.guide#435]
Repository: https://github.com/subkrish/opensource.guide
Preview: https://subkrish.github.io/opensource.guide/ (Doesn't exist yet, will be updated)
Locale: `hi-IN`

On your fork:

- [ ] Update `title`, `description`, and `locale` in `_config.yml`, and push the branch to the `gh-pages` branch of your fork. This should build the website and it should be visible at the preview url above.
- [ ] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [ ] Create a new directory in `_articles/` for your locale and translate each guide:
  - [ ] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [ ] starting-a-project.md
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by srishag** [comment]
I can help with this!

**Comment by itsN1X** [comment]
many freeBSD and UNIX ( < 3.11.1 ) don't support la_hindi-tf rendering. It'd be nicer if we embibe the svgs' with hindi inline.
Superfast render, A2Z-compat !
@subkrish still up on this one?

**Comment by MikeMcQuaid** [comment]
@subkrish Apologies this issue has been neglected for so long. I've merged the first translation to this repository (Spanish) and updated the documentation on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please submit a pull request when you have translated all articles and checked `./script/test` passes and I'll get it merged in ASAP. Thanks!
