### ISSUE TITLE
Translation: Brazilian Portuguese

### ISSUE THREAD

**Issue by rogeriopradoj** [github/opensource.guide#446]
Repository: https://github.com/rogeriopradoj/opensource.guide
Preview: https://rogeriopradoj.github.io/opensource.guide/
Locale: `pt-BR`

On your fork:

- [x] Update `title`, `description`, and `locale` in `_config.yml`, and push the branch to the `gh-pages` branch of your fork. This should build the website and it should be visible at the preview url above.
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [ ] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [ ] starting-a-project.md
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by williamcspereira** [comment]
Hi, I would like to contribute translating. I've forked your repository https://github.com/rogeriopradoj/opensource.guide

**Comment by nayafia** [comment]
Hi @rogeriopradoj and @williamcspereira! It looks like there's a Brazilian Portuguese translation underway on https://github.com/github/opensource.guide/issues/342, so I'd encourage you to combine efforts over there. :blush:
