### ISSUE TITLE
Ebook Version

### ISSUE THREAD

**Issue by elbaulp** [github/opensource.guide#449]
It would be great if we can made a ebook version of the site. I've been wanting to read the entire guide for some time now, but I do not really like spend much time reading on the screen. I could try to convert the posts into a `.mobi` version using pandoc or this project: https://github.com/mccormicka/md-book

Currently I can send each individual page to my kindle using tinderizer, but a complete ebook of the guide would be great.

What do you think?

**Comment by nayafia** [comment]
Hi @elbaulp! That sounds great, feel free to go for it and let us know how it turns out. :blush:

**Comment by elbaulp** [comment]
Ok, I'll try to do it withing a week or two.

**Comment by MikeMcQuaid** [comment]
Closing this out as I think it's out of scope for this repo as-is and the only attempt so far (https://github.com/github/opensource.guide/pull/458) has stalled, sorry!
