### ISSUE TITLE
Translation: Korean

### ISSUE THREAD

**Issue by minwook-shin** [github/opensource.guide#451]
Repository: https://github.com/minwook-shin/opensource.guide
Preview: https://minwook-shin.github.io/opensource.guide/
Locale: `ko-KR`

On your fork:

- [x] Update `title`, `description`, and `locale` in `_config.yml`, and push the branch to the `gh-pages` branch of your fork. This should build the website and it should be visible at the preview url above.
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [x] Create a new directory in `_articles/` for your locale and translate each guide:
  - [x] best-practices.md
  - [x] building-community.md
  - [x] code-of-conduct.md
  - [x] finding-users.md
  - [x] getting-paid.md
  - [x] how-to-contribute.md
  - [x] leadership-and-governance.md
  - [x] legal.md
  - [x] metrics.md
  - [x] starting-a-project.md
- [x] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [x] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by minwook-shin** [comment]
hello. everyone!
i'm korean translator.
korean translation is in progress. but, cname(kr.opensource.guide) does not work, and because of this, the preview link does not work.
help me, github staffs!

**Comment by minwook-shin** [comment]
Changed the cname file.
(kr.opensource.guide -> ko.opensource.guide)

**Comment by nayafia** [comment]
@bkeepers this one's for you!

**Comment by minwook-shin** [comment]
Translated best-practices.md.

**Comment by minwook-shin** [comment]
I removed cname for testing. Thank you for your understanding.

**Comment by minwook-shin** [comment]
@nayafia @clarkbw 
hello..? completed the Korean translation. And i clicked PR buttons. Please confirm. Thank you!

**Comment by minwook-shin** [comment]
updated locale...!. ko -> ko-kr (config.yml, cname)

**Comment by MikeMcQuaid** [comment]
Closing in favour of PR in #514; will continue talking there.
