### ISSUE TITLE
Another README guide

### ISSUE THREAD

**Issue by dguo** [github/opensource.guide#452]
Hello! I recently created a [small website](https://www.makeareadme.com/) to explain what a README is and elaborate on what makes for a good one. Would there be any interest in adding it to the guide's [README section](https://opensource.guide/starting-a-project/#writing-a-readme)?

**Comment by mlinksva** [comment]
Well done! As for adding it, see https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md#ground-rules--expectations

> Please don't add references or links to things you or your employer have created as others will do so if they appreciate it.

**Comment by dguo** [comment]
Ah, sorry for missing that part. Understood.
