### ISSUE TITLE
Translation: Bengali

### ISSUE THREAD

**Issue by nasirkhan** [github/opensource.guide#465]
Repository: https://github.com/nasirkhan/opensource.guide
Preview: https://nasirkhan.github.io/opensource.guide
Locale: `bn-BD`

On your fork:

- [x] Update `title`, `description`, and `locale` in `_config.yml`, and push the branch to the `gh-pages` branch of your fork. This should build the website and it should be visible at the preview url above.
- [x] Copy `_data/locale/en-US.yml` to a new file with the name of your locale and translate the strings
- [ ] Create a new directory in `_articles/` for your locale and translate each guide:
  - [ ] best-practices.md
  - [ ] building-community.md
  - [ ] code-of-conduct.md
  - [ ] finding-users.md
  - [ ] getting-paid.md
  - [ ] how-to-contribute.md
  - [ ] leadership-and-governance.md
  - [ ] legal.md
  - [ ] metrics.md
  - [ ] starting-a-project.md
- [ ] Update `CNAME` to include your locale (e.g. de.opensource.guide)

Once a translation is completed:

- [ ] Open a Pull Request on the [upstream repository](https://github.com/github/opensource.guide) to add your fork to `translations` in `_config.yml`

**Comment by nayafia** [comment]
@bkeepers this one's for you!

**Comment by UNGM2000** [comment]
Possible to conversation work API development.

**Comment by MikeMcQuaid** [comment]
@nasirkhan Apologies this issue has been neglected for so long. I've merged the first translation to this repository (Spanish) and updated the documentation on the latest translations approach (https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md). Please submit a pull request when you have translated all articles and checked `./script/test` passes and I'll get it merged in ASAP. Thanks!
