### ISSUE TITLE
Pointing outdated information as something to be careful

### ISSUE THREAD

**Issue by igorsteinmacher** [github/opensource.guide#468]
I would like to add a section talking about how the obsolescence of documentation can affect newcomers to the best-practices.md

I'd love to add more in terms of how to make a supportive/welcoming community. I have been researching newcomers onboarding to open source issues for such a long time (more on www.igor.pro.br). I really appreciate the efforts of your project, and would like to offer myself to help you guys

Here is what I propose:

**Identify and dismiss outdated information**

If it is hard to keep documentation up-to-date, community members should remove outdated information or, at least, clearly identify it as outdated. Outdated documentation demotivates newcomers, as per [a research conducted recently](http://www.igor.pro.br/publica/papers/2014CHASE.pdf). By clearly pointing the absence or obsolescence of documents, communities can ask for help to update or create such documentation.

**Comment by nayafia** [comment]
Hi @igorsteinmacher, thanks for the suggestion! I could see this fitting into the `Document your processes` section, in the section before `Write down your project's vision`.

Feel free to open a PR with your suggestions. Could you condense it down a bit, to maybe 1-2 short sentences, to fit the rest of that section?

Also, [per our contributing guide](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md#ground-rules--expectations):

> When adding content, please consider if it is widely valuable. Please don't add references or links to things you or your employer have created as others will do so if they appreciate it.

While the paper you linked to looks quite interesting, we have a policy of not adding things you've created yourself. Thanks!

**Comment by igorsteinmacher** [comment]
Thanks a lot for the comment @nayafia 👍 
I will shorten it and remove the link to the paper to create the PR.

**Comment by MikeMcQuaid** [comment]
Done in https://github.com/github/opensource.guide/pull/470, thanks @igorsteinmacher.
