### ISSUE TITLE
(more detailed) guide lines on issue management

### ISSUE THREAD

**Issue by lorenzwalthert** [github/opensource.guide#476]
This seems like a cool project. I was looking for somehow detailed implementation guide lines on issue management - in particular, on how to label issues of an open-source project. I note that under Section 3 in Practices for Maintainers, you have a paragraph related to it:

> If your project already suffers from a large backlog, @steveklabnik has suggestions for how to triage issues efficiently.

In [styler](https://github.com/r-lib/styler), an open-source project I was recently contributing to, I figured out that using a coherent set of labels can help you a great deal with organising issues - and I think they are underrated. I hence started [saamwerk](https://github.com/lorenzwalthert/saamwerk) that contains one resource that describes [a strategy to label issues](https://github.com/lorenzwalthert/saamwerk/blob/master/issue-management/labelling-strategy.md). Do you think it would make sense to link it here?

**Comment by nayafia** [comment]
Hi @lorenzwalthert! Thanks for your suggestion. [Per our contributing guide](https://github.com/github/opensource.guide/blob/gh-pages/CONTRIBUTING.md#ground-rules--expectations), we don't accept self-nominations for resources:

> When adding content, please consider if it is widely valuable. Please don't add references or links to things you or your employer have created as others will do so if they appreciate it.

However, if you'd like to contribute a paragraph on how to think about/use labels as a maintainer, that could be useful, either under the Best Practices section you reference, or perhaps [Building Communities](https://opensource.guide/building-community/#meet-contributors-where-theyre-at), depending on your focus 😊

**Comment by lorenzwalthert** [comment]
Thanks @nayafia, should have read all of your contributing guide then 😊. I am actually also happy to add it with some other existing project, it's just that I have not found one quickly where it would fit. So I guess we can close that issue then.

**Comment by nayafia** [comment]
👌 thanks @lorenzwalthert!
