### ISSUE TITLE
Sharing a project

### ISSUE THREAD

**Issue by danthareja** [github/opensource.guide#481]
Hey there!

I recently released a project that aims to let users apply they concepts they learn in phenomenal guides like this.

https://github.com/danthareja/contribute-to-open-source

In this project, users are given tests and tasked with writing code to DRY up an existing codebase. When they submit a PR, there's some fun back and forth with a bot that interprets their CI results and eventually merges their code.

*(in fact, you'll see that I shamelessly ripped the copy from your "What happens after you submit a contribution" - I love that section)*

I'm looking to expand the reach of this project to new contributors, and thought I'd start with one of the most credible sources on the subject. Is there any room in your guide for a link to my project?

**Comment by MikeMcQuaid** [comment]
Sorry @danthareja, we discourage self-submission of your own content. If it becomes widely useful, others may decide to submit it.

**Comment by danthareja** [comment]
Fair enough, thank you @MikeMcQuaid.
