### ISSUE TITLE
Add tips on tracking the number of open issues

### ISSUE THREAD

**Issue by infotexture** [github/opensource.guide#491]
Under [Retention](https://opensource.guide/metrics/#retention), the Metrics guide [suggests](https://github.com/github/opensource.guide/blame/gh-pages/_articles/en-US/metrics.md#L99) tracking the number of open issues and pull requests: 

> If these numbers get too high, you might need help with issue triaging and code reviews.

The GitHub UI doesn't currently offer a way to view the development of these metrics over time _(like for contributions, commits, or code frequency)_. 

Many maintainers may be feeling overwhelmed by what feels like a large number of open issues, but without a way to see how many were open last year or two years ago, they're left to rely on memory or gut feelings rather than hard data.

There are many commercial options that claim to offer burndown charts or similar visualizations of historic issue data, but it seems like an "opensource.guide" should point to open source solutions that can be used to keep track of whether the overall issue load is increasing or decreasing.

Can we recommend anything here or provide more information about how to go about that?

— or should we open an issue to add a new **Issues** chart to the **Insights** tab of the GitHub UI?

**Comment by nayafia** [comment]
Hi @infotexture! If you have open source solutions that you'd like to add to the Metrics guide, that'd be great. However, this repo isn't the right place for discussing GitHub feature requests.

Closing this out for now, but if you have specific additions to the Metrics guide that you'd like to suggest, feel free to open a PR.
