### ISSUE TITLE
Are public GitHub projects open source?  - contradiction with terms of service?

### ISSUE THREAD

**Issue by culmat** [github/opensource.guide#495]
In my understanding, 
as of https://github.com/github/opensource.guide/blob/gh-pages/_articles/en-US/legal.md#are-public-github-projects-open-source a public repository without license may not be used, copied, modified, or contributed back to.

Where as of https://help.github.com/articles/github-terms-of-service/#5-license-grant-to-other-users
"By setting your repositories to be viewed publicly, **you** agree to **allow others to** view and "fork" your repositories (this means that others may **make their own copies** of Content from your repositories in repositories **they control**)."

Wouldn't this mean that by publishing the repository on GitHub you explicitly allow anybody to transfer owner ship by forking.

I personally prefer the latter ;-)

**Comment by mlinksva** [comment]
Control of a repo != ownership of the IP in that repo. I'm afraid your preference is not reality. :smile:

I'll make a PR in a moment that might address the sense that you have that there's a contradiction.

**Comment by culmat** [comment]
Hi Mike,
thanks for you quick answer.
I am a litte surprised. https://github.com/ presents its service as _Built for developers_ and _A better way to work together_ with a strong focus on team work.
I am also a great fan of the fork -> pull-request ->merge workflow that has been made popular (if not invented?) by github. 

If nobody is allowed to change content of a repository without license I have the following propositions to improve your service.
- propose a permissive default license when creating a new repository. Most of you users want collaboration but are no lawyers. We need help to use the platform correctly.
- don't give users write permission on forks of such a repositories. At least warn them that they might infringe rights. Or are you trying to trap us into something? ;-)
- warn owners of repositories without license before they merge a pull request or add a contributor. 
By doing so, they loose the right to pursue their own work. _[That means nobody can use, copy, distribute, or modify their contributions -- and that "nobody" includes you."](https://github.com/github/opensource.guide/blob/gh-pages/_articles/en-US/legal.md#why-do-people-care-so-much-about-the-legal-side-of-open-source)_
This sentence - if true - needs to go into the github UI before bad things happen.


In my mind github is where code lives through contributions. Its not a history book of code written by others.
Keep up the great work and so will we!
Kind regards
Matthias

**Comment by mlinksva** [comment]
@culmat I'll pass your good suggestions along, thanks.

This repo isn't intended for GitHub feature discussions but for what it's worth new license-related features are released from [time to time](https://github.com/blog/search?q=license).
