### ISSUE TITLE
Translation: Nepalese 

### ISSUE THREAD

**Issue by Roshankd1** [github/opensource.guide#525]
My mother tongue is Nepalese and also I am a fluent English speaker. I graduated with Finance Degree from University in the UK. 

I really look forward to pursuing career as a programmer.

**Comment by caolyhuynh** [comment]
100,000

**Comment by Roshankd1** [comment]
sorry @caolyhuynh 
whats 100,000?

**Comment by MikeMcQuaid** [comment]
@Roshankd1 We'll accept pull requests to add this translation: https://github.com/github/opensource.guide/blob/gh-pages/docs/translations.md
