### ISSUE TITLE
Repo referenced in 'Avoiding name conflicts' has an issue

### ISSUE THREAD

**Issue by IBLoud** [github/opensource.guide#540]
Text 'Check for open source projects with a similar name' refers to repo: https://github.com/LogIN-/ospnc

Issue [22](https://github.com/LogIN-/ospnc/issues/22) and [23](https://github.com/LogIN-/ospnc/issues/23) should be addressed or another repo referenced for this section of the guide.

**Comment by MikeMcQuaid** [comment]
Even although it's unmaintained http://ivantomic.com/projects/ospnc/ is still working.
