### ISSUE TITLE
Incomplete Korean Translations

### ISSUE THREAD

**Issue by willysr** [github/opensource.guide#553]
in ko.yml, these text are not yet translated
`format: "[code] with [love] by [github] and [friends]"`

cc @minwook-shin

**Comment by minwook-shin** [comment]
@willysr , Thanks to this issue, I translated some untranslated data text!

**Comment by MikeMcQuaid** [comment]
Thanks for the issue @willysr and for @minwook-shin fixing it in https://github.com/github/opensource.guide/pull/554.
