### ISSUE TITLE
Typo (Spanish guide translation)

### ISSUE THREAD

**Issue by marcorichetta** [github/opensource.guide#566]
This is located at the [Spanish contribution guide](https://opensource.guide/es/how-to-contribute/)

LCENSE should be LICENSE [Link](https://github.com/github/opensource.guide/blob/master/_articles/es/how-to-contribute.md#una-lista-de-verificaci%C3%B3n-antes-de-que-contribuyas)

Also, the link that appears at the bottom of the page [Contribuir](https://github.com/github/opensource.guide/edit//_articles/es/how-to-contribute.md) is broken

**Comment by MikeMcQuaid** [comment]
@marcorichetta Thanks! Could you submit a pull request for these changes?

**Comment by marcorichetta** [comment]
@MikeMcQuaid I made the pull request but I don't know if I made it right.
It needs a reviewer but I can't add one.
Thanks anyway!

**Comment by ZHEXIONGHAN** [comment]
I made the pull request but I don't know if I made it right.
It needs a reviewer but I can't add one.
Thanks anyway

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/github/opensource.guide/pull/567, thanks @marcorichetta!

FYI the reviewer just means someone working for GitHub needs to approve and then merge your PR.
