### ISSUE TITLE
Link to contribute broken

### ISSUE THREAD

**Issue by rbstrachan** [github/opensource.guide#569]
### Description
At the very bottom of the website, there is a link to contribute to this repository. When clicked, it leads to a 404 Error.

### Steps to Reproduce

1. Go to `opensource.guide`
2. Scroll to very bottom of webpage
3. Click `Contribute` link

**Expected behavior:**
Redirect to this (?) repository.

**Actual behavior:**
404 Error

**Additional Information:**
I have read the [contributing guidelines](https://github.com/github/opensource.guide/blob/master/CONTRIBUTING.md), however, I did not create a pull request as I am usure as to where the broken link is actually supposed to redirect.

**Comment by MikeMcQuaid** [comment]
Thanks for the report! Fixed in https://github.com/github/opensource.guide/pull/568.
