### ISSUE TITLE
Add a section, dev grants, ethical advertising on Getting Page

### ISSUE THREAD

**Issue by owocki** [github/opensource.guide#585]
Hi there.

Kevin Owocki here from [Gitcoin](https://gitcoin.co) -- Our mission is to grow open source with incentivization mechanics.

I was wondering if the repository maintainers would be open to our opening up a PR to add a few more thoughts about crowdfunding, ethical advertising, dev grants, etc to the [Getting Paid page](https://opensource.guide/getting-paid/). 

Thanks,
Kevin

**Comment by MikeMcQuaid** [comment]
@owocki If that PR doesn't make any references to Gitcoin: we'd be open to that. If someone unaffiliated with Gitcoin adds the reference in future that would be OK but we're pretty strict on avoiding self-promotion. Thanks!

**Comment by owocki** [comment]
hey Mike, I totally understand.  thanks for letting me know the guidelines here.
