### ISSUE TITLE
Subscribe form doesn't work

### ISSUE THREAD

**Issue by fv3rdugo** [github/opensource.guide#589]
In the "Stay in touch" form at the bottom of the https://opensource.guide/ page:
Subscribe doesn't work.
I do not know if it is here to report it.
Thanks in advance.

**Comment by MikeMcQuaid** [comment]
Can you elaborate on how it doesn't work? I see "thanks for subscribing"? Do you have JavaScript enabled in your browser? What browser is it?

**Comment by fv3rdugo** [comment]
I'm sorry, I should have given more details. 
With Firefox 59.0.2 (64 bits) it didn't work, however with Chrome Version 65.0.3325.181 (Official Assembly) (64 bits) has worked well. In both JavaScript it's enabled.

**Comment by fv3rdugo** [comment]
I found the problem in Firefox browser: tracking protection blocked JavaScript.

The resource of the site has been blocked «https://github.us11.list-manage.com/subscribe/post-jsonXXXX» because the protection against tracking is enabled.
