### ISSUE TITLE
address poorly maintained projects

### ISSUE THREAD

**Issue by jowagner** [github/opensource.guide#617]
The guide so far doesn't address the delicate task of getting an unmaintained or poorly maintained project back on track when one isn't (yet) part of the maintainer team. There are many projects out there that have a small but significant user base and no or inadequate maintenance. Forking is unattractive as one cannot continue with the old project name, website and source code repository. A take-over attempt can easily get messy and fail. Some guidance how to best approach such situations would be useful.

**Comment by mlinksva** [comment]
See #289 for some related prior discussion.

**Comment by ramadankini** [comment]
Request Change

**Comment by jowagner** [comment]
@ramadankini: Please elaborate. Are you requesting a change, do you suggest that I should request a change, what change...?

**Comment by ramadankini** [comment]
Nothing.

..Ignore that typos

**Comment by khai1996** [comment]
unable the device by qualxom

**Comment by honemepool** [comment]
Opp

**Comment by honemepool** [comment]
Please

**Comment by Benerdchia** [comment]
#617

**Comment by Seilamuk** [comment]
Something support

**Comment by Benerdchia** [comment]
#617

**Comment by walka69** [comment]
https://github.com/github/opensource.guide/issues/617

**Comment by MikeMcQuaid** [comment]
Thanks for the issue! We're not currently creating new guides at this time. My personal advice in those situations would be forking the project and, if the fork gets enough steam, considering renaming the project.
