### ISSUE TITLE
Open Source Guides LOGO

### ISSUE THREAD

**Issue by k-syusteem** [github/opensource.guide#618]
### Hello @everyone!

Currently there is a special logo / icon owned by Open Source Guides?

**Comment by solarsystem1817** [comment]
@k-syusteem

**Comment by mlinksva** [comment]
If you're asking whether an Open Source Guides logo exists, I don't see one. 😄 

Feel free to be more specific and ask again if you had a different question.

**Comment by k-syusteem** [comment]
I will design it for you, is it possible?

**Comment by mlinksva** [comment]
Hi @k-syusteem thanks for the offer but I don't think we're looking for a project logo at this time.
