### ISSUE TITLE
Write a guide about stepping down and taking on ownership

### ISSUE THREAD

**Issue by shazow** [github/opensource.guide#62]
Perhaps a section towards the end about stepping down as the maintainer and how to gracefully hand it off to somebody else? Things to do, things not to do, how to make sure the project is ready for the transition for when/if the time comes.

I have some feelings and experiences about this that I haven't written up yet, not sure if there is already much content on the topic elsewhere?

Also perhaps another tangential or separate section about deprecation.

**Comment by lee-dohm** [comment]
From @thejameskyle in #290:

> We talked at @maintainerati about creating a guide to document how to properly change ownership of a project from both the perspectives of the original maintainer and the new one
> 
> - How to communicate with the original maintainer about expectations and goals
> - How to ensure that the new maintainer will be successful
> - What to do when the original author is unavailable
> - What steps to take to make sure users are not negatively affected
> - How to maintain a good relationship with the original maintainer
> 
> Tons of stuff to this, but this is a good amount to start with

**Comment by nayafia** [comment]
More useful bits on this topic: https://speakerdeck.com/bkeepers/tending-your-open-source-garden-v2

**Comment by nayafia** [comment]
Bummed to close this out, but we can re-open when we're able to take on writing a new set of guides.
