### ISSUE TITLE
Help for translation?

### ISSUE THREAD

**Issue by petrk94** [github/opensource.guide#628]
Hello,

I would like to help here to translate the website to german, can I contribute here for that?

Thanks

**Comment by mlinksva** [comment]
Instructions at https://github.com/github/opensource.guide/blob/master/docs/translations.md

**Comment by mlinksva** [comment]
Oh, see #577 for a German translation in progress. Perhaps you can help?

**Comment by petrk94** [comment]
thank you @mlinksva
