### ISSUE TITLE
Address new bounty platforms as a way for getting paid for time working on open source

### ISSUE THREAD

**Issue by jschiarizzi** [github/opensource.guide#638]
New platforms like gitcoin (its not a currency) and Bounties Network are homes to funded issues that open source projects want help on.  This is also used to recruit developers interested in those projects.

Would be added to https://opensource.guide/getting-paid/#funding-your-own-time

I don't work for these platforms but I do like them a lot, and have been paid for contributing to open source for the first time via them. I wanted to make an issue for discussion if something like this should be linked in this guide, since they companies.  Although, we are already including links to patreon and kickstarter in this section, which similarly are companies.

**Comment by jschiarizzi** [comment]
@mlinksva who else can we get to look at this and #639?

**Comment by mlinksva** [comment]
Let's try pinging @nayafia who is the expert and probably wrote much of this guide (but no longer has any obligation with the project, feel free to ignore). 🙇

**Comment by nayafia** [comment]
Thanks for the ping! Left a review on #639.

While I'm not personally in love with bounty programs, I recognize they've become increasingly popular especially among crypto projects. @jschiarizzi I really like that 1) you included specific examples of successful bounties, 2) the change is well-written overall, and 3) this isn't a self-promotional contribution, so all that makes me 👍 on adding it in. Thanks for suggesting these edits!

**Comment by jschiarizzi** [comment]
Thank you for taking the time to look at that @nayafia. I recognize that this may seem a bit spammy, which is why I also opened an issue with the PR
