### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by tripcall** [github/opensource.guide#694]
Hi Everyone,

I've been looking for ways to contribute to an Open Source project and found amazing information through Open Source Guide, so I would like to know if it is of any interest a Brazilian Portuguese Translation.

Best Regards,

**Comment by mlinksva** [comment]
Absolutamente! (No idea if that's idiomatic. :smile:)

See our brief doc on [starting a new translation](https://github.com/github/opensource.guide/blob/master/docs/translations.md).

**Comment by tripcall** [comment]
Hey Mike,

Thanks for the reply.

Great Portuguese, you can use Absolutamente, but it is not that usual, a more usual or informal way would be "Claro!" or "Com certeza!" :)

I'm following the new translation steps, so, hope to send a pull request as WIP very soon.

Hope to contribute in a meaningful way.

Thanks a lot !

**Comment by MikeMcQuaid** [comment]
Yes, this would be great, thanks!
