### ISSUE TITLE
Add First Contributions

### ISSUE THREAD

**Issue by Ifyokoh** [github/opensource.guide#739]
I want to add [First contributions](https://github.com/firstcontributions/first-contributions) to this project.  
First contributions helps beginners get started with contributing to open source projects and it helped me personally as a beginner and first timer to make my first contribution [here](https://github.com/Ifyokoh/first-contributions)  It was so straight forward and hands-on you can contribute in less than ten minutes with suggestions on what to work on next and a slack community to help/ mentor beginners. 
I would love to make a pull request to add it to your list of resources that helps beginners and first timers to contribute because it is a very good tutorial to get started.

**Comment by MikeMcQuaid** [comment]
Thanks for the suggestion! We'll accept a PR to add this.
