### ISSUE TITLE
Как удалить сгенерированный код мой личный кабинет F.W.A.M.

### ISSUE THREAD

**Issue by 11581536** [github/opensource.guide#753]
Прошу у кого помощь меня исследование чтоб удалить личный кабинет сгенерированный код, хочу открыть ЛК!!!

**Comment by Iosunlock** [comment]
Languages

**Comment by jaymifoster** [comment]
[translated_code.pdf](https://github.com/github/opensource.guide/files/2569023/translated_code.pdf)
