### ISSUE TITLE
Typesetting error in Chinese pages rendering using Firefox

### ISSUE THREAD

**Issue by zhaiyusci** [github/opensource.guide#789]
Hi!
I find a problem when I use Firefox browsing the Chinese translation of the guide.
The problem can be easily found if look at the screen shot I upload.  In Firefox, the Chinese subtitles do not wrap.  In Chrome, they behave properly.  No such issue in English page.
I am using Firefox 64.0.

![Screen sot](https://user-images.githubusercontent.com/3461548/50471556-36574200-09f0-11e9-891b-19da30899cf5.png)

**Comment by mlinksva** [comment]
Hi @zhaiyusci thanks for the bug report! I can reproduce this; direct link to URL screenshot is taken of https://opensource.guide/zh-cn/how-to-contribute/#what-it-means-to-contribute

It seems to have to do with `keep-all` introduced in https://github.com/github/opensource.guide/pull/714

It looks like this improves Chrome's word breaking for CJK but causes Firefox to not break at all, at least in some cases? I don't really know anything about this subject area and quick searching doesn't help me. Hopefully someone who knows something will know how to fix!

**Comment by fujisawakazuhiro** [comment]
keep-all

**Comment by lqez** [comment]
I will try to figure out. Thanks for CC.

**Comment by mlinksva** [comment]
@lqez fixed this with #792, thanks!

If any Chinese or Japanese expert wishes to enable specifically for those languages as @lqez did for Korean in #792 and get working in both Firefox and Chrome, they can in the future.
