### ISSUE TITLE
node_modules not on .gitignore

### ISSUE THREAD

**Issue by leolleocomp** [github/opensource.guide#793]
I've faced this when working on  #715 . I've checked out the [master's .gitignore](https://github.com/github/opensource.guide/blob/master/.gitignore) and it also doesn't list node_modules. Is there any reason behind that? I mean, my branch right now is tracking every change on npm packages, and I'm wondering if this is the desired result and why.

**Comment by shiftkey** [comment]
@leolleocomp I'd take in a PR that ignores `node_modules` and removes what's currently in there.

**Comment by leolleocomp** [comment]
> @leolleocomp I'd take in a PR that ignores `node_modules` and removes what's currently in there.

Going to take this path, thank you.

**Comment by jillmarie350** [comment]
It will do what it says to do if you follow the directions

**Comment by jillmarie350** [comment]
I have no more to say

**Comment by kenyonj** [comment]
This breaks GitHub Pages so it is being added back in with https://github.com/github/opensource.guide/pull/798

**Comment by leolleocomp** [comment]
> This breaks GitHub Pages so it is being added back in with #798

Hi @kenyonj , thanks for the observation! 

Do you know any workaround on this issue, or if it's really necessary?

**Comment by kenyonj** [comment]
It looks like our design systems team is looking into it. There are a couple of alternatives, some better than others, and I'll make sure to update this issue once we decide which way to proceed.

**Comment by MikeMcQuaid** [comment]
Thanks for the issue @leolleocomp but as mentioned above this is needed for GitHub Pages and I don't see a pressing need to change this.
