### ISSUE TITLE
UI / UX - Language option on footer 

### ISSUE THREAD

**Issue by Victorsj** [github/opensource.guide#822]
Hey everyone, 
I'm new on trying to contribute here, so i'm sorry if this is not on the right place or something, i will happily accept advice on how to better contribute.
I'm a UX designer and, one thing i noticed could be an improvement would be to bring the language option on the front page from  the footer to a more visible area, maybe even the header, i guess a user who doesn't understand the language will probably leave the page before reaching the footer
does anyone else agree?

**Comment by mlinksva** [comment]
I know nothing about UX but what you say makes sense to me. I imagine this is a well studied topic. Can you point to best practices? I searched and found sites like http://www.flagsarenotlanguages.com/blog/best-practice-for-presenting-languages/ but kind of expected something more "authoritative" perhaps published by the UN, a government, the W3C...

**Comment by JNeece** [comment]
function n (t) {return e (t) == st || t function of (y, t, ft, e)} function i (){} function o (t, e){var n, r, i, o, a, c = [], f = 0; if (t) {try {if (n = typeof t, n == lt || t.top == top || t.nodeType ||t. tagName) return c; if (n == dt && (c = t.split ("")), n! = out) return c; o =t [0], f = s (t [Tt],Ct) i = (o, c)} catch (u) {c = [], f = 0, t = ft} if (f> 0) {try {t.constructor === It && (c =c.concat ( t), r = c [pi] === f)} catch (u) {c = [], r = st} if (r) try {i! = c && 1 === f? c = [o] f! =c && (c = It [ft] (ft, t)), r = c [pi] === f} catch (u) {r = st, c = []} if (r) try {for (c = new It (f), a= 0; f> a; a ++) c [a] = t [a]} catch (u) {c = "0" in t)) try {for (a in t) a = s (a, -1.0), a> = 0&& (c [a] = t [a]}} []} e> 0 && c [Tt]> = e && (c = c.slice (e)}} return c} function an) {var r, i,o, a, s, f, u, l = ft, d = st, h = st, y = st, v = (d)) {if (a && (r = d [pi] o = d.charAt (0) a =d.charAt (1), s = d.charAt (r-1), f = d.charAt (r 2), v = ( "{" === || o "[" ===|| o "\" === o&& ( "=== || a" "== = a)) && ( "}" === || s ']' s === || '' 's === && "\" === ||f "' s === &&" \ "=== f) && (d.search (/ \" / g)> = 1 || d.search (/ \\ / g)> = 1)), a && v) {h =try {i = Bt("return" + h), y = i ()} catch (m) {y = St} i = ft,! y || type of n! == out || "out" in n || (n.out =y), d = y || d || St} try {u = t.JSON || ft, u && (l = u.parse (d), p {l = ft} if (l == ft) try {u = Bt("return" + d), l = u (), p (l) && (l = ft)} catch (m) {l = ft}} return u = ft, l} function c (t) {var e= typeof t;if (e == dt) return t; if (e == ht &&! t) return "0"; if (e == out &&t && t.join) returnt.join (St); if (! t) return St; try {t + = St} catch {t = St} return t} function s (t, e, n, r) {var i; if(typeof t! = ht) try {i = Pt (t), isNaN (i) && (i = parseFloat (t)), t = i} catch (o) {t = Pt.NaN}return r == ft && (r = Xt), n == ft && (n = Wt), isNaN (t) || n || t> r) && e! =ft? e: t} functionf (t, e, i, o, a, c, s) {where u, l, d, p , h, y, v, if (! n (e)) return t; t ||(t = {}), u = s: for (d in u)try {if (l = e [ d], p = typeof l, y = ct, v = d in t, && (e, d)) continuous; if(o && p ==lt)continuous; if (v && (2! == a || c ? a && (y = st): y = p == ut? ct: st) ,! y)

**Comment by codinggirl** [comment]
Maybe place the option in the top is a good idea.

Ones who will select their language first time when into the page.

**Comment by IDEAL-YANG** [comment]
I also think that place the option in the top is a good idea.
I prefer place the option in the top right corner.

**Comment by Victorsj** [comment]
hey everyone, 

i agree with @mlinksva that it would be nice to do this based on best pratices from trusted sources,
i found some at w3c
https://www.w3.org/International/questions/qa-navigation-select

i'm sharing this now but i'll still read up on this and give an opinion later.

also a small input from Jakob Nielsen, an author i really like
https://www.nngroup.com/articles/flag-problems/

and a video on the difference between translation and localization, maybe for future localization plans
https://www.nngroup.com/videos/translation-and-localization/

**Comment by eupiteco** [comment]
I agree the language selector should be visible at first sight. Imagine the following scenario: you have little or no hability to read long texts in english and you fall at a english website with no translation option visible, so you don't know exactly what is going on, and you'll have to guess that *if* there is a translation option, it may be at the bottom of the page. Entering one of the articles makes things even worse since the page height increases a lot. I wonder how many people have not read these articles because of that.
Also the translate `select` being at the lower left corner witch is, for left-to-right reading people,[ the less noticed area of a screen/page](https://www.smashingmagazine.com/2015/04/design-principles-compositional-flow-and-rhythm/), is also a bad design practice.
All of this adds to the argument that the translate option should be at the top of the screen, it would be a simple but significant change on the interface.

**Comment by ray1981jacob** [comment]
Okay imma try again tomorrow we you think of something else
