### ISSUE TITLE
helping the very beginners to open source

### ISSUE THREAD

**Issue by TheOptimisticCoder** [github/opensource.guide#836]
<a href="https://opensource.guide">Open Source Guide</a> helps beginners to contribute to open source. It makes us understand the workflow. But is it really helping the very beginners ? By very beginner I want to say someone who is very new to technology and want to contribute the real code because these very beginners get a little bit frustrated if they are not able to contribute some code.
If that very beginner can get some information about how much and what type of knowledge he/she should have in order to contribute real code to an open source project then I guess it will be easier for them to set a goal or something and start contributing to open source. By this we can help them not feel upset and the goal will keep them motivated instead.

**Comment by MahaTareyuga** [comment]
my roommate played the balloon game where she/they just bumped balloons
around all day.. [] o \ | its just boxes :) music. And a twitch stream from
someone named shibbaya when you sorta forget your mantra |> g2g my gf wants
me to lie for bit... | "          "

**Comment by TheOptimisticCoder** [comment]
@MahaTareyuga what do you wanna say ?

**Comment by MikeMcQuaid** [comment]
Thanks for the issue @TheOptimisticCoder but we're not catering for the absolute very beginners you describe here.

**Comment by guanwenlng** [comment]
{"error":{"code":"9301","message":"어플리케이션 인증에 실패하였습니다. :: requestedAppKey is null and ApiType is 01","request":"/v1.0/rac/ps/allocation.json","service":"system"}}
