### ISSUE TITLE
http://github.com/tumblr/policy/commits/master/community-guidelines.txt

### ISSUE THREAD

**Issue by Dferdi1199** [github/opensource.guide#849]
Open source text

**Comment by sumon30427** [comment]
I'm md Shahidul islam, as a software Creator with proprietor of the networking home. Which created at first digital note's book, note'spad at "2013" as demo for circular including attachment in it's Gmail i.d <sumon304@gmail.com> organization globally in the worldwide. My demo comparing another's but, my demo was first class with as a great successful workings jobs, that's the time i'm have been number one in the globally. Everybody's seeing the demo with commander how the will be unbelievable networking life ill the software's products. Enterprises created of myself at first my life. After then I'm winning globally in the  networking all sites "property the home" control powers in my hand. At 2013" The homes I'm don't sales any others, that's the times i getting a server name is "atom" ?<xmls 1.0 but, from another's place another persons alltimes flow up me of device's and hacking/theif  of my "home's" "atom server"
& my hardworking successful note'sbook copy. But original copy keeping of my device sing tech hard disks. Today's at ended of story. Another day again circularing all the details. How can position of finance feedback? I don't known the figure of amounts!

**Comment by talsafran** [comment]
Reported the above as off topic. Closing.
