### ISSUE TITLE
Leadership and Governance > Table of Contents

### ISSUE THREAD

**Issue by Joannis** [github/opensource.guide#883]
The table of contents doesn't fold out at all. See the attached images:

<img width="253" alt="Screenshot 2019-03-22 at 18 55 27" src="https://user-images.githubusercontent.com/1951674/54843174-12945700-4cd4-11e9-86a5-4598552a6ae7.png">

<img width="272" alt="Screenshot 2019-03-22 at 18 56 20" src="https://user-images.githubusercontent.com/1951674/54843228-3061bc00-4cd4-11e9-8a29-dff43504334c.png">

**Comment by Joannis** [comment]
The issue was not solved.

**Comment by MikeMcQuaid** [comment]
Fixed by https://github.com/github/opensource.guide/pull/939
