### ISSUE TITLE
bug: Top Navbar right borders

### ISSUE THREAD

**Issue by co16353sidak** [github/opensource.guide#896]
URL: https://opensource.guide

1. the top navbar seems very inconsistent with the overall theme of the whole webpage. in the screenshots, I feel that the link borders span completely from the top to bottom whereas everywhere else there is an offset present. I feel that an offset could be present.
<img width="1274" alt="Screenshot 2019-03-30 at 8 18 11 PM" src="https://user-images.githubusercontent.com/35738138/55277701-f4100a80-5328-11e9-9392-6d27d970f490.png">
<img width="1032" alt="Screenshot 2019-03-30 at 8 25 21 PM" src="https://user-images.githubusercontent.com/35738138/55277782-f32ba880-5329-11e9-8e59-c0c3d11323e0.png">

2. in mobile resolutions, the top nav-links seems to left align which leaves a side padding on top, this could be better implemented if we centre-aligned the navbar the wrapper div.
<img width="488" alt="Screenshot 2019-03-30 at 8 39 01 PM" src="https://user-images.githubusercontent.com/35738138/55277944-ddb77e00-532b-11e9-9c13-3482ecaf5148.png">

**Comment by MikeMcQuaid** [comment]
Will review a PR for this, thanks!

**Comment by co16353sidak** [comment]
@MikeMcQuaid, to be clear, should I send a PR with the proposed changes ?

**Comment by MikeMcQuaid** [comment]
@co16353sidak Yes, please. I'm afraid I cannot guarantee it'll be merged but it's easier to discuss a PR than an issue with this sort of thing. Thanks ❤️
