### ISSUE TITLE
mention-bot is now archived

### ISSUE THREAD

**Issue by leventov** [github/opensource.guide#898]
The guide mentions https://github.com/facebookarchive/mention-bot which is now an archived project.

**Comment by DrBeta** [comment]
I did not find that link anywhere in the project.

**Comment by DrBeta** [comment]
@bruce If you can, can you close this

**Comment by leventov** [comment]
Here: https://opensource.guide/best-practices/

**Comment by DrBeta** [comment]
Now I see it.

**Comment by DrBeta** [comment]
#908 Should fix this if it gets merged

**Comment by talsafran** [comment]
👋 

This was addressed in https://github.com/github/opensource.guide/pull/908, and the choice was to leave the mention of `mention-bot` since that could still be useful to readers, in lieu of other alternatives. Thanks for the report @leventov I think we'll close this out for now 🙌

**Comment by heroInCommunity** [comment]
A bit of self-promoting:
@leventov  I have created a SaaS, which is free for open source projects efficiefy.io/
It does not support for now comments in PR (as I wanted to ask as less privileges as possible), but it has ability to message to Slack with recommended reviewers.

**Comment by DrBeta** [comment]
@heroInCommunity that kind of stuff doesnt belong on a GitHub issue, if you want to self promote there are many options where people will actually consider using your platform instead of instantly dismissing it because you are advertising on a random GitHub issue
