### ISSUE TITLE
Could not find jekyll-watch from rubygems.org

### ISSUE THREAD

**Issue by co16353sidak** [github/opensource.guide#899]
While working on a PR related to styling changes, I have been trying to set up the project using `script/bootstrap` but unfortunately it prompts that.
`Could not find jekyll-watch-2.2.0 in any of the sources` 
this happens when it tries to fetch metadata from `rubygems.org` website regarding all the packages. 

<img width="682" alt="Screenshot 2019-04-02 at 11 19 15 AM" src="https://user-images.githubusercontent.com/35738138/55379053-28f2ac00-5539-11e9-9cd9-f14d2466e927.png">

I have also gone through the website `rubygems.org` and the the package is already listed on the webpage.

<img width="1272" alt="Screenshot 2019-04-02 at 11 20 52 AM" src="https://user-images.githubusercontent.com/35738138/55379111-63f4df80-5539-11e9-9153-df4503c0a213.png">

This could be a problem related to my machine specifically so I could use some help.

**Comment by MikeMcQuaid** [comment]
> This could be a problem related to my machine specifically so I could use some help.

Sorry, we can't provide additional help to individuals here.

**Comment by MikeMcQuaid** [comment]
Actually reopening as this is also affecting https://github.com/github/opensource.guide/pull/885
