### ISSUE TITLE
Dependency issues with primer-core index.scss

### ISSUE THREAD

**Issue by co16353sidak** [github/opensource.guide#905]
While working on a PR, I was compiling and running the server commands to setup a local environment for the website. but in doings it gave me a few dependency errors, listed as followed in the screenshot
<img width="571" alt="Screenshot 2019-04-06 at 9 36 29 PM" src="https://user-images.githubusercontent.com/35738138/55672047-0b647000-58b4-11e9-9767-180c86af557e.png">

there is a need to shift the call of these resources to the file `grid.scss` which feels to me like a manual process and something on which I can work on (if you guys give me the go ahead) 🥇

**Comment by talsafran** [comment]
@co16353sidak thanks for reporting this! Looks like this deprecation warning is known (see: https://github.com/primer/css/issues/741) and will appear even on the latest version of Primer until there is an alternative shipped for future deprecation warnings, like https://github.com/primer/css/issues/740.

Appreciate you flagging this! You rock 🙌
