### ISSUE TITLE
404 error reported on inter-UI fonts.

### ISSUE THREAD

**Issue by co16353sidak** [github/opensource.guide#906]
On loading the website both locally and through the link,both the console and the terminal reports a 404 error on a couple of fonts.
the exact errors are listed on the screenshots below.

terminal:
<img width="589" alt="Screenshot 2019-04-06 at 9 42 29 PM" src="https://user-images.githubusercontent.com/35738138/55672121-e15f7d80-58b4-11e9-8922-1a3c52b46485.png">

browser console:
<img width="492" alt="Screenshot 2019-04-06 at 9 42 37 PM" src="https://user-images.githubusercontent.com/35738138/55672125-e7555e80-58b4-11e9-98ea-083e8a727f6a.png">

**Comment by matawinb** [comment]
#929

**Comment by Yokymia32** [comment]
Good

**Comment by talsafran** [comment]
@co16353sidak thanks for reporting this! Yesterday I shipped a fix for these errors in #943, really appreciate you being thoughtful in your report! ✨
