### ISSUE TITLE
Security.MD as a community best practice

### ISSUE THREAD

**Issue by jhutchings1** [github/opensource.guide#981]
One thing that seems to be missing from the open source guide at the moment is any information about how to handle security disclosures. We (GitHub) just released a feature called the [security policy](https://help.github.com/en/articles/adding-a-security-policy-to-your-repository), which uses a file called `security.md` to allow maintainers to tell users how to handle disclosure. 

It's easy enough to document that, but I'd love to get more content in place about what should go into a security policy in general. There's a bunch of content out there on this including [HackerOne's policy builder](https://hackerone.com/policy-builder/), the [NTIA Coordinated Vulnerability Disclosure template](https://www.ntia.doc.gov/files/ntia/publications/ntia_vuln_disclosure_early_stage_template.pdf) and [Securitytxt.org](https://securitytxt.org). 

Do we have consensus on what the necessary parts of the policy should be? I'd love to start by building that list, then we can build this out into an article. 

cc: @jobertabma @edoverflow @mijuhan @philipturnbull

**Comment by EdOverflow** [comment]
> Do we have consensus on what the necessary parts of the policy should be?

For the actual content of a security policy, maybe it would be worth looking at what the resources linked to above suggest and cherry picking what works best for the open-source community.

When you register for a new program on HackerOne, the default/template policy consists of the following sections:

- Disclosure Policy 
- Exclusions 
- Safe Harbor 

[HackerOne's policy builder](https://hackerone.com/policy-builder/) appears to consist of:

- Brand Promise
- Scope
- Process
- Safe harbor
- Preferences

security.txt files contain the following directives:

- Contact
- Encryption
- Acknowledgments
- Preferred-Languages
- Canonical (Note: This is very `security.txt` specific.)
- Policy
- Hiring

security.txt in itself is not a security policy and more of a sitemap to point security researchers in the right direction to find the necessary materials for submitting reports. This includes a `Policy:` directive that points to the project's security policy (e.g., `SECURITY.md` file).

A good best practice that I would personally like to see is a security.txt integration for GitHub Pages that points to the project's `SECURITY.md` file. Some users, including me, [use custom domains with GitHub Pages](https://help.github.com/en/articles/using-a-custom-domain-with-github-pages). This means it is not always apparent that the project runs on GitHub; therefore, I would suggest having a simple security.txt file generator as seen on https://securitytxt.org/ in the "Security" tab of a repository that creates a file with the `Policy:` directive pointing to the repository's `SECURITY.md` policy.

![image](https://user-images.githubusercontent.com/18099289/58746967-d3694b80-8464-11e9-84a1-b0e44ff4edf7.png)
<p align="center"><i>Figure 1: A security.txt file generator in the "Security" tab.</i></p>

In addition to the security.txt integration, I think it is crucial we educate users on how "Safe Harbors" work. Currently, HackerOne's policy builder does not link to external resources for users to learn more about the legalese surrounding the vulnerability disclosure process. Maybe a link to the "Legal safe harbor" section of @philipturnbull's blog post ["Five years of the GitHub Bug Bounty program"](https://github.blog/2019-02-19-five-years-of-the-github-bug-bounty-program/#legal-safe-harbor) could help. I am just worried that if we do not explain what "Safe Harbors" are, we might end up with projects quickly generating policies with safe-harbor verbiage without them adhering to it. (cc: @Amitelazari)

![image](https://user-images.githubusercontent.com/18099289/58747140-3bb92c80-8467-11e9-9d98-d2b69ccb270a.png)
<p align="center"><i>Figure 2: "Safe Harbor" section of HackerOne's policy builder.</i></p>

**Comment by F-Jennings** [comment]
> I am just worried that if we do not explain what "Safe Harbors" are, we might end up with projects quickly generating policies with safe-harbor verbiage without them adhering to it.

I<sup>*</sup> quite like the idea of allowing projects to include safe-harbor verbiage, even if there's no way to be sure projects fully understand & adhere to their generated safe-harbor policies. Neither is ideal, but (if the safe-harbor template verbiage is good) "policy exists but project didn't adhere to it" is still legally easier to deal with than "project has no written policy at all."

That said, fully & enthusiastically agreed that it would be helpful to link to somewhere people can find information on what a safe-harbor is in this context, what it may or may not cover, etc. That way, projects will have access to the information they need to make informed choices about their safe-harbor policy language.


<sup> \*: speaking for myself, not for any employer/client(s) </sup>

**Comment by jhutchings1** [comment]
Thanks everyone! I went ahead and made a first draft of this documentation based on the discussion above. Feel free to comment/contribute there! #985

**Comment by jyangchisyan** [comment]
> Thanks everyone! I went ahead and made a first draft of this documentation based on the discussion above. Feel free to comment/contribute there! #985

Do you intend to add tasks list fill up other languages translator list or generate another issue to contribute to this new page?

**Comment by jhutchings1** [comment]
Not quite done yet stalebot. Will get back to this soon!
