### ISSUE TITLE
Add persian language

### ISSUE THREAD

**Issue by BaseMax** [github/opensource.guide#995]
Hey @Github,

I'm Max, As a github [maintainers ](https://github.com/maintainers/)member.

We are begin to translate and write the text...
**Target:** Persian, Farsi (فارسی)

I will send some new pull requests... (https://github.com/MaxFork/opensource.guide/tree/fa)
No any problem and limitation for this language? @MikeMcQuaid

Regards,
Max

**Comment by MikeMcQuaid** [comment]
All good, thanks! Look forward to your PR!

**Comment by loverdeveloper** [comment]
i want to be a part of this.

**Comment by BaseMax** [comment]
> 
> 
> i want to be a part of this.

Hey Mohmmad Najafian @loverdeveloper,

Wait until the first version of this done,
Next you can improve or change it.

Regards,
Max
