### ISSUE TITLE
The website title display  wrong information on the language page

### ISSUE THREAD

**Issue by jyangchisyan** [github/opensource.guide#998]
I found a little bug on the website title. When I switch other languages page, the website title will change and appear the wrong information.

__Expect (correct on English page)__: 
<img width="813" alt="螢幕快照 2019-06-26 下午10 53 54" src="https://user-images.githubusercontent.com/4977932/60194098-4bac0c80-986b-11e9-9058-9bb5c2d385f8.png">

__Wrong Title__:
<img width="846" alt="螢幕快照 2019-06-26 下午10 54 08" src="https://user-images.githubusercontent.com/4977932/60194301-a2194b00-986b-11e9-8967-a21f4bda3319.png">

__How to Fix__:

It could add title config in lang index.html like below:

```
---
layout: index
title: 開源軟體指南
lang: zh-tw
permalink: /zh-tw/
---
```

the behavior will like this.
<img width="562" alt="螢幕快照 2019-06-26 下午11 32 31" src="https://user-images.githubusercontent.com/4977932/60194425-e4db2300-986b-11e9-813d-c1aa374420f9.png">

Have any other idea for modifying the website title?

**Comment by mlinksva** [comment]
You're right, thanks for noticing and filing an issue. Want to make a PR with your suggested fix?

**Comment by jyangchisyan** [comment]
#1011  Hi @mlinksva, I pushed it and I hope other contributors could assist confirm the translation is correct in several languages.
